### DISCUSSION TITLE
Different token timeouts for clients

### DISCUSSION THREAD

**Discussion by rdavyd** [dexidp/dex#1975] [Q&A] [answered]
Hi,

I've looked through a sample config file, but did not find this.
Is there a way to set different token expiry timeouts for various static clients. For example, client1 has 24h token expiry, client2 has 30days?

**Comment by nabokihms** [comment, marked as answer]
Hello! There is no such feature yet. Expiration policies can only be configured globally through the config.

Example of `expiry` section: 
```yaml
expiry:
  deviceRequests: "5m"
  signingKeys: "6h"
  idTokens: "24h"
```
