### DISCUSSION TITLE
connectors/oidc: mapping the non-standard claims to standard one

### DISCUSSION THREAD

**Discussion by morarucostel** [dexidp/dex#1998] [Q&A]
Hello, 
We are using [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) together with dex and would like know if it is possible to get the standard claims like `given_name` and `family_name` back into id_token returned by dex? 

The oauth2-proxy is configured to use dex as the issuer-url, and dex is configuring the real IdP as an oidc connector with 
```yaml
  connectors:
  - config:
      clientID: XXXXXXXX
      clientSecret: YYYYYYYY
      issuer: real_idp_issuer_url
      redirectURI: real_dex_callback
    id: idp_staging
    name: idp staging
    type: oidc
```
The jwt returned by the IdP is something like: 
```
{
    "s_hash": "some-hash-here",
    "sub": "emailaddress@domain.com",
    "name": "John Doe",
    "firstName": "John",
    "emailAddress": "John.Doe@domain.com",
    "lastName": "Doe",
    "aud": "value-here",
    "iat": numeric-value-here,
    "exp": numeric-value-here
....
  }
```
and the jwt returned by dex to oauth2-proxy is:
```
{
  "at_hash": "some-hash-here",
  "aud": "oauth2-proxy",
  "email": "John.Doe@domain.com",
  "email_verified": true,
  "exp": numeric-value-here,
  "iat": numeric-value-here,
  "iss": "https://domain/dex",
  "name": "John Doe",
  "preferred_username": "John.Doe@domain.com",
  "sub": "edited-value"
}
```

Is there any way either in dex's configuration, or via claimMapping or any other way, to map the `firstName` claim from the IdP's jwt to dex's issued jwt either as standard or non-standard claim?
So, basically, we would like to get back from dex, part of the id_token, also the firstName and lastName as given_name and family_name. What should we change in the configuration?
