### DISCUSSION TITLE
how to configure authentication through Google

### DISCUSSION THREAD

**Discussion by gy95** [dexidp/dex#2017] [Q&A] [answered]
The below two params should replace with parameters or just remain unchanged
```
clientID: $GOOGLE_CLIENT_ID
clientSecret: $GOOGLE_CLIENT_SECRET
```

my config-dev.yaml is as follows:
```
connectors:
- type: mockCallback
  id: mock
  name: Example
- type: google
  id: google
  name: Google
  config:
     issuer: https://accounts.google.com
     clientID: $GOOGLE_CLIENT_ID
     clientSecret: $GOOGLE_CLIENT_SECRET
     redirectURI: https://127.0.0.1:5554/dex/callback
     hostedDomains:
     - $GOOGLE_HOSTED_DOMAIN
```

what else should i do to configure authentication through Google?
Thanks.
