### DISCUSSION TITLE
OIDC connector claimMapping has no impact

### DISCUSSION THREAD

**Discussion by michalvanco** [dexidp/dex#2158] [Q&A]
Hi folks,

I have a question about the possibilities how to troubleshoot the situation when the `claimMapping` configuration of OIDC connector has no impact and keeps the original value.

My situation:
 * I have deployed dex which has following claims supported:
```
"claims_supported": [
  "aud",
  "email",
  "email_verified",
  "exp",
  "iat",
  "iss",
  "locale",
  "name",
  "sub"
]
```
 * I have configured OIDC connector other provider like:
```
connectors:
- type: oidc
  id: idp-test
  name: Custom OIDC
  config:
    issuer: https://<HOST>
    clientID: <CLIENT-ID>
    clientSecret: <SECRET>
    redirectURI: https://<DEX-HOST>/dex/callback
    scopes:
    - email
    - profile
    - openid
    - customBase
    getUserInfo: true
    insecureSkipEmailVerified: true
  claimMapping:
    email: customEmailID
```
 * the connected provider has following claims supported:
```
"claims_supported": [
  "aud",
  "iss",
  "sub",
  "iat",
  "exp",
  "acr",
  "auth_time",
  "email",
  "email_verified",
  "name",
  "family_name",
  "given_name",
  "customEmailID",
],
```
 * required claim `customEmailID` is part of the `customBase` scope

After the connector configuration is applied to dex, claim mapping after logging in custom provider has no effect (I can see that the information is released from provider).

I also tried some other variants like `email: "customBase:customEmailID"` or `email: sub` but I am always getting the original value.

Is there alternatively some way how to troubleshoot such OIDC integration? e.g. to see exactly what claims are being returned with which values etc.?

Dex version: v2.27.0

Thank you in advance for any help.

**Comment by nabokihms** [comment]
It looks like you need to indent the `claimMapping` field a little more.
example:
```yaml
connectors:
- type: oidc
  id: idp-test
  name: Custom OIDC
  config:
    issuer: https://<HOST>
    clientID: <CLIENT-ID>
    clientSecret: <SECRET>
    redirectURI: https://<DEX-HOST>/dex/callback
    scopes:
    - email
    - profile
    - openid
    - customBase
    getUserInfo: true
    insecureSkipEmailVerified: true
    claimMapping:
      email: customEmailID
```
You can find the example with a detailed description here https://dexidp.io/docs/connectors/oidc/#configuration

**Reply by michalvanco** [reply]
Thanks @nabokihms for the hint, anyway it is still behaving the same and I am not getting the value I expect in `email`.

I tried again:
```
claimMapping:
  email: customEmailID
```
and
```
claimMapping:
  email: "customBase:customEmailID"
```
(which one is correct btw..?)

Thanks!

**Reply by nabokihms** [reply]
The first one seems correct.

**Comment by michalvanco** [comment]
We have just discovered in the code that the `claimMapping` is only applied the original claim is not available.

https://github.com/dexidp/dex/blob/master/connector/oidc/oidc.go#L304-L310

But this is not the case here, we actually want to change the default mapping of `email` claim to other `claim`.

So we have `customEmailID` and `email` and we would like to use `customEmailID` as the right claim for `email`.

@nabokihms - that should be doable in either in specific code above or by using other configuration option (so that the behavior is properly described).

Thanks!

**Reply by nabokihms** [reply]
In fact, it's me who should thank you. I opened an issue to track the problem
https://github.com/dexidp/dex/issues/2162

**Comment by jonra82** [comment]
I'm also having troubles with claim mapping. I have a Dex instance connected to a ADFS 2019 server. When I authenticate against Dex and ADFS I get an exception about "missing name claim". I know ADFS does not return a "name: something" claim. I can see it when I inspect the id-token it returns. In the token it has claims:

{
  "upn": "some@something.com",
  "unique_name": "addomain\\username",
  }

I want Dex to map the upn claim to name.

In Dex Config I have the following:

```
- config:
  id: adfs
  name: adfs
  type: oidc
  config:
    issuer: https://fs.something*/adfs
    clientID: someclientid
    clientSecret: somesecret
    redirectURI: https://somethingdex/callback
    scopes:
    - profile
    - email
    - groups
    - openid
    - allatclaims
    insecureEnableGroups: true
    getUserInfo: true
    insecureSkipEmailVerified: true
    claimMapping: #this seems to have no effect, Dex still complains about missing name claim
      name: upn #this seems to have no effect, Dex still complains about missing name claim
```
any tips?

**Reply by jonra82** [reply]
Nevermind, got this working!

**Reply by jblom** [reply]
@jonra82 I got exactlty the same problem. I want to map my idp's `nickname` to `name`, since my idp does not have a `name` claim. So I'm doing that like so:

```
overrideClaimMapping: true
claimMapping:
   name: nickname
```

But it keeps complaining `Failed to authenticate: missing "name" claim`.

Curious to hear how you solved this

**Reply by jblom** [reply]
ah nevermind :p I got it to work by adding the setting:

```
userNameKey: nickname
```

**Reply by arjunchatla88** [reply]
> Nevermind, got this working!

How did you resolve this ? . We are having the same issue with Dex .

**Reply by jblom** [reply]
@arjunchatla88 so the mapping for the "name" claim can be fixed by using `userNameKey: your-idps-name-field`

However mapping other fields (so: custom claims issued by my idp and mapping them to standard claims) really don't work for me:

```
    config:
              issuer: https://your-idp.com
              clientID: $YOUR_CLIENT_ID
              clientSecret: $YOUR_CLIENT_SECRET
              overrideClaimMapping: true  # this stuff does nothing for me
              claimMapping:  # so this whole claimMapping block does not work at all
                website: idp  # try to map idp from https://your-idp.com to the website field.
              redirectURI: https://your-service/callback # works
              userNameKey: nickname  # This however does work!
              getUserInfo: true # this stuff also works
              insecureEnableGroups: true # this stuff also works
              insecureSkipEmailVerified: true # this stuff also works
```
