### DISCUSSION TITLE
OIDC login fails with error CSIAQ0179E

### DISCUSSION THREAD

**Discussion by ghost** [dexidp/dex#2231] [Q&A] [answered]
Hi,

I am using Dex in our ArgoCD instance for OIDC SSO and getting this error:

```bash
level=error msg="Failed to authenticate: consent_required: CSIAQ0179E The system could not prompt for user consent.
```

when trying to login with argocd cli `argocd login --sso`. Meanwhile web ui login works perfectly fine.

This is my config:

```yaml
dex.config: |
    connectors:
      - type: oidc
        id: myid
        name: maid 
        config:
          issuer: https://endpoint/oidc/endpoint/default
          clientID: myclientid
          clientSecret: $dex.w3id.clientSecret
          scopes:
            - profile
            - email
            - groups
          getUserInfo: true
          insecureEnableGroups: true
          claimMapping:
            groups: "blueGroups"
```

Any idea how to solve that? Thank.
