### DISCUSSION TITLE
Failed to query provider "http://127.0.0.1:5556": Get http://127.0.0.1:5556/.well-known/openid-configuration: dial tcp 127.0.0.1:5556: connect: connection refused

### DISCUSSION THREAD

**Discussion by alexkayzer** [dexidp/dex#2260] [Q&A]
Hello!
I'm using dex on docker-compose
after run i can't get access on  http://127.0.0.1:5556

my dex-k8s-authenticator logs
`Failed to query provider "http://127.0.0.1:5556": Get http://127.0.0.1:5556/.well-known/openid-configuration: dial tcp 127.0.0.1:5556: connect: connection refused
`

command: dex serve /etc/dex/config.yaml --web-http-addr 127.0.0.1:5556

dex conf:
```
connectors:
- config:
    bindDN: <cn>
    bindPW: <pass>
    groupSearch:
      baseDN: <my data>
      nameAttr: cn
      userMatchers:
      - groupAttr: member
        userAttr: DN
    host: <ldaphost>
    insecureNoSSL: true
    insecureSkipVerify: true
    userSearch:
      baseDN: <basedn>
      emailAttr: mail
      filter: (objectClass=person)
      idAttr: DN
      nameAttr: cn
      username: uid
    usernamePrompt: LDAP Username
  id: ldap
  name: LDAP
  type: ldap
issuer: http://127.0.0.1:5556/
logger:
  level: debug
storage:
  type: sqlite3
web:
  address: 127.0.0.1:5556
staticClients:
- id: k8s-cluster2-stage
  redirectURIs:
  - 'http://127.0.0.1:5555/callback/k8s-cluster1'
  name: 'k8s-cluster1'
  secret: 'ZXhhbXBsZS1hcHAtc2VjcmV0'
```

dex-auth.conf:

```
clusters:
  - name: k8s-cluster1
    namespace: default
    short_description: "Cluster1 stage"
    description: "Cluster1 stage env"
    redirect_uri: http://127.0.0.1:5555/callback/k8s-cluster1
    client_secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    client_id: k8s-cluster1
    issuer:  http://127.0.0.1:5556
    k8s_master_uri: https://k8s-cluster1-api:6443
    static_context_name: false
    k8s_ca_pem: |
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
listen: http://127.0.0.1:5555
web_path_prefix: /
```
