### DISCUSSION TITLE
Configure dex session timeout for argocd

### DISCUSSION THREAD

**Discussion by MikeK184** [dexidp/dex#2267] [Q&A] [answered]
Hi there, I've been trying to configure the dex.config thats included in argocd to have a session timeout after a given time. But the token the user gets assigned is always valid till the session ends.
![image](https://user-images.githubusercontent.com/56921065/132297795-3648fbba-6066-40cd-85df-26fc5e99540a.png)

've tried a couple of ways to set the expiry date/time but unfortunately the expiry date never changes. My knowledge of dex is very limited so I've been just trying Expiry settings I've found on the [dex documentation](https://dexidp.io/docs/id-tokens/#expiration-and-rotation-settings). My dex.config in argocd looks like this:

```
  dex.config: |
    connectors:
      - type: ldap
        id: ad
        name: Active-Directory
        config:
          host: XXX
          insecureSkipVerify: true
          bindDN: XXX
          bindPW: $ldap.bindPW
          expiry: 
            idTokens: "5m"
            deviceRequests: "2m"
            signingKeys: "1m"
            refreshTokens:
              absoluteLifetime: "5m"
          userSearch:
            baseDN: XXX
            filter: "(objectClass=person)"
            username: userPrincipalName
            idAttr: DN
            emailAttr: mail
            nameAttr: sn
          groupSearch:
            baseDN: XXX
            filter: "(objectClass=group)"
            userAttr: DN
            groupAttr: member
            nameAttr: cn

```

**Comment by nabokihms** [comment, marked as answer]
Hello! 
1. expiration settings should be on the same level as the settings of the connectors.
```
dex.config: |
    expiry: 
      idTokens: "5m"
      deviceRequests: "2m"
      signingKeys: "1m"
      refreshTokens:
        absoluteLifetime: "5m"
    connectors:
      - type: ldap
        id: ad
        name: Active-Directory
        config:
          host: XXX
          insecureSkipVerify: true
          bindDN: XXX
          bindPW: $ldap.bindPW
          userSearch:
            baseDN: XXX
            filter: "(objectClass=person)"
            username: userPrincipalName
            idAttr: DN
            emailAttr: mail
            nameAttr: sn
          groupSearch:
            baseDN: XXX
            filter: "(objectClass=group)"
            userAttr: DN
            groupAttr: member
            nameAttr: cn
```

2. Do not set the `signingKeys` lifetime to small intervals. Something like `6h` is fine.
