### DISCUSSION TITLE
[k8s][gitlab] Invalid 'state' parameter provided: not found

### DISCUSSION THREAD

**Discussion by Chup4Chups** [dexidp/dex#2402] [Q&A]
Hi guys,

I am doing PoC with dex on kubernetes using the example-app and our self-managed gitlab instance.
I followed below documentation:
- https://dexidp.io/docs/kubernetes/
- https://dexidp.io/docs/connectors/gitlab/

I replaced github connector by gitlab:
```
 connectors:
    - type: gitlab
      id: gitlab
      name: GitLab
      config:
        baseURL: https://gitops
        clientID: $GITLAB_APPLICATION_ID
        clientSecret: $GITLAB_CLIENT_SECRET
        redirectURI: https://dex.example.com:32000/callback
        useLoginAsID: false
```

I started the example app:
```
$ example-app --issuer https://dex.example.com:32000 --issuer-root-ca ../k8s/ssl/ca.pem --redirect-uri https://dex.example.com:32000/callback --client-id $GITLAB_APPLICATION_ID  --client-secret $GITLAB_CLIENT_SECRET --debug
```

So far, I can access Example-App, see Gitlab connector and the redirection goes well until I see a ​"Bad Request, Requested resource does not exist" (status code 400)

k8s side, I can see from dex pods logs that the conection is succesfull but there is a "state" issue:

```
time="2022-02-07T12:27:23Z" level=info msg="config issuer: https://dex.example.com:32000"
time="2022-02-07T12:27:23Z" level=info msg="kubernetes client apiVersion = dex.coreos.com/v1"
time="2022-02-07T12:27:23Z" level=info msg="creating custom Kubernetes resources"
[...]
time="2022-02-07T12:27:23Z" level=info msg="config storage: kubernetes"
time="2022-02-07T12:27:23Z" level=info msg="config static client: Example App"
time="2022-02-07T12:27:23Z" level=info msg="config connector: gitlab"
time="2022-02-07T12:27:23Z" level=info msg="config connector: local passwords enabled"
time="2022-02-07T12:27:23Z" level=info msg="config skipping approval screen"
time="2022-02-07T12:27:23Z" level=info msg="config refresh tokens rotation enabled: true"
time="2022-02-07T12:27:23Z" level=info msg="listening (https) on 0.0.0.0:5556"
2022/02/07 12:28:01 http: TLS handshake error from 192.168.65.3:53792: remote error: tls: unknown certificate
time="2022-02-07T12:28:05Z" level=info msg="login successful: connector \"gitlab\", username=\"John Doe\", preferred_username=\"John.Doe\", email=\"john.doe@toto.com\", groups=[\"devops-team\"]"
time="2022-02-07T12:28:05Z" level=error msg="Invalid 'state' parameter provided: not found"
time="2022-02-07T12:32:23Z" level=info msg="garbage collection run, delete auth requests=0, auth codes=3, device requests=0, device tokens=0"
```

Any idea where this **"Invalid 'state' parameter provided: not found"** come from ?
I found similar closed [issue #1466](https://github.com/dexidp/dex/issues/1466) but no solution provided....
