### DISCUSSION TITLE
LDAP client side failover

### DISCUSSION THREAD

**Discussion by iaean** [dexidp/dex#2541] [Ideas]
We are happily using Dex LDAP to inject AD groups into ID Tokens.

Is there interest to implement client side LDAP failover?

LDAP reference libraries like [OpenLDAP][0] providing the feature to specify a list of LDAP servers. Usually the first one that works will used.

[0]: https://linux.die.net/man/5/ldap.conf

```yaml
connectors:
- type: ldap
  config:
    # today, as far as we know
    host: ldap.example.com
    # improvement
    host: ldap1.example.com, ldap2,example.com
```

It seems an important feature for enterprise users.

Thanks for your feedback.
Best regards.
