### DISCUSSION TITLE
Using groups[] from staticPasswords

### DISCUSSION THREAD

**Discussion by iaean** [dexidp/dex#2542] [General]
We are happily using Dex LDAP to inject AD groups into ID Tokens.

Is there a way to inject `groups[]` utilizing the `staticPasswords` method?

```yaml
staticPasswords:
  - name: "John Doe"
    email: "john@example.com"
    username: "john"
    # maybe like this...
    groups:
    - admin
    - guest
    # echo "foobar" | htpasswd -n -B -C 10 -i john | cut -d: -f2
    hash: "$2y$10$p1qG2vVSvfxWVbpUFnQIYeD5neYrsaMWyNR9snGPJR9p6U8KEd.j2"
```

This would make development with LDAP/AD much more easier because you don't need to deal with a real LDAP instance during development.

Thanks for your feedback.
Best regards.
