### DISCUSSION TITLE
How to add additional claims to Dex token from upstream oidc token

### DISCUSSION THREAD

**Discussion by addevine** [dexidp/dex#2596] [Q&A]
Using the oidc connector to login to upstream Okta, I'd like to include a "clients" claim to the Dex JWT. Is there a way to add this claim from the upstream oidc token to the Dex token?

Logging in with Okta oidc provides a claim named "clients" in its token
`{
  ....
  "clients": ..,
  ....
}`

However the token from Dex does not include this "clients" claim. Is there a way to add it? I've tried claim mappings to made groups map to clients, but as shows below there is not even a groups in this Dex token.
`{
  "iss": "...",
  "sub": "...",
  "aud": "...",
  "exp": ...,
  "iat": ...,
  "at_hash": "...-",
  "email": "...",
  "email_verified": ...,
  "name": "..."
}`

**Comment by nabokihms** [comment]
Hello, @addevine.

1. At the current time, there is no way to add custom claims to a dex id token. We want to implement this logic in the future as a part of solving this issue https://github.com/dexidp/dex/issues/1635
2. I assume your application does not send the `groups` scope, so there is no groups claim in the token.

**Reply by addevine** [reply]
Thank you for the response! Correct, the app is not sending groups (they put what would I'd expect to be in groups in some custom claim named "clients"). Do you think if we can have the upstream oidc provider send an empty group claim, we could then use dex claim mapping to map the custom claim to the groups?

`
claimMapping:
  groups: "clients"
`

If not, I need to see if they can just use groups instead of their custom claim, but I have no control over the app hence why I'm trying the above solution! Thank you!

**Reply by nabokihms** [reply]
I think this is not your upstream provider case. Your application needs to request the `groups` scope on login. You must provide scopes via a GET parameter when you redirect a user from your application page to Dex for a login procedure. 

There is an example of an authentication request to Dex:
```web
http://127.0.0.1:5556/dex/auth
  ?client_id=example-app  <-- client to use
  &redirect_uri=http://127.0.0.1:5555/callback    <-- your app callback address
  &scope=groups+openid+profile+email+offline_access  <-- must include groups
  &response_type=code
  &state=I+wish+to+wash+my+irish+wristwatch
```

**Comment by SpiderUnderUrBed** [comment]
I am trying to add a custom user permissions claim to dex, but looking at this discussion, I am wondering if supported for custom claims has been added since this discussion was made?
```
issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: axum-app
    secret: axum-app-secret
    name: Axum Test App
    redirectURIs:
      - http://localhost:8083/oidc/callback

connectors:
  - type: mockCallback
    id: mock
    name: Mock
```
Here I would like to add a user permission claim, is that supported yet?
