### DISCUSSION TITLE
different access levels for different github teams

### DISCUSSION THREAD

**Discussion by KrawczowaKris** [dexidp/dex#3177] [Q&A]
Hello,

we use authentication via GitHub SSO, configured using `dex` and `oauth2-proxy`. This is used on multiple resources using the following ingress annotations:

```
nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.example.com/oauth2/start
nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.example.com/oauth2/auth
```
Members of GitHub teams `team1` and `team2` have access to all resources. Is there a way to make one of the resources available to `team3`, but make the rest of the resources inaccessible to it?

dex configuration:

```
config:
  issuer: https://dex.example.com
  connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: client-id
        clientSecret: client-secret
        redirectURI: https://dex.example.com/callback
        orgs:
          - name: organization-name
            teams:
              - team1
              - team2
```

oauth2-proxy configuration:

```
config:
  existingSecret: oauth2-proxy-client
  extraArgs:
    provider: oidc
    oidc-issuer-url: https://dex.example.com
    scope: openid profile email groups
    skip-provider-button: true
    cookie-domain: .example.com
    whitelist-domain: .example.com
    redirect-url: https://oauth2-proxy.example.com/oauth2/callback
    code-challenge-method: S256
```
