### DISCUSSION TITLE
skipApprovalScreen stopped working in version 2.40.0

### DISCUSSION THREAD

**Discussion by xzizka** [dexidp/dex#3611] [General]
We were using Dex 2.38.0 with the following config (anonymized).
```
connectors:
  - type: ldap
    name: Active Directory
    id: ad
    config:
      <multiline AD configuration>
enablePasswordDB: false
issuer: https://dex.<issuer_URL>
oauth2:
  skipApprovalScreen: true
  passwordConnector: ad
staticClients:
  - id: kubernetes-k8s
    redirectURIs:
      - 'http://localhost:8000'
      - 'http://localhost:18000'
      - 'https://localhost:8080/auth/callback'
      - '/device/callback'
      - 'https://<dashboard_url_callback>/oauth2/callback'
    name: 'Kubernetes'
    secret: <kubernetes_scret>
    public: false
  - id: argocd-k8s
    name: ArgoCD
    redirectURIs:
      - 'http://localhost:8085/auth/callback'
      - 'https://<argo_callback_url>/auth/callback'
    secret: <argo_secret>
    public: false    
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  tlsCert: /<cert_path>/tls.crt
  tlsKey: /<cert_path>/tls.key
```
If we use it with dex:v2.38.0, the approval screen with "Grant Access" is skipped. When we upgraded to version 2.40.0 keeping the same configuration the "Grant Access" screen is not skipped and we need grant the access by clicking on the button.

I was checking these discussions:
- [https://github.com/dexidp/dex/issues/3540](https://github.com/dexidp/dex/issues/3540)
- [https://github.com/dexidp/dex/pull/3086](https://github.com/dexidp/dex/pull/3086)
- [https://github.com/dexidp/dex/issues/3540](https://github.com/dexidp/dex/issues/3540)

In the last issue there was mentioned, that the issue was caused by `approval_prompt=force` setting, but we don't use it anywhere.

I am not sure, if I miss any config changes or if this is a bug. As it can be seen here (https://github.com/dexidp/dex/issues/3540#issuecomment-2115244565) I am not the only one with the issue.
In version 2.39.0 was implemented this change:
[https://github.com/dexidp/dex/pull/2897](https://github.com/dexidp/dex/pull/2897)
It looks the issue started with the version where the issue was implemented.

We use Dex internally and we don't need the approval screen. In our case it is annoying.
Is there any configuration, that needs to be set except the `skipApprovalScreen`, to disable the approval screen in version 2.40.0?
