### DISCUSSION TITLE
No bearer token in browser requests

### DISCUSSION THREAD

**Discussion by fhajiyev** [dexidp/dex#3750] [Q&A]
Hello,
I am running Dex server (port 5556) with my Spring Boot app (port 8085) locally, and my Spring Boot oauth2 creds look like this:

```
  security:
    oauth2:
      client:
        provider:
          dex:
            authorization-uri: http://localhost:5556/dex/auth
            token-uri: http://localhost:5556/dex/token
            jwk-set-uri: http://localhost:5556/dex/keys
        registration:
          dex:
            client-id: sample-app
            client-secret: ZXhhbXBsZS1hcHAtc2VjcmV0
            client-name: Sample App
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8085/my-api/login/oauth2/code/dex

```
When I type one of my GET endpoints in the browser, I get redirected to Dex login page, I input my user creds, and see "Grant access" button. After pressing it, I see the GET response, and subsequent requests do not require login BUT there is no token in their headers.
I wonder why that happens, shouldn't there be a token in every request after authorization?

This is my filter chain in Spring Security config:

```
@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        
            http
                .authorizeRequests()
                .antMatchers("/login/oauth2/code/dex").permitAll()
                .anyRequest().authenticated()
                .and()
                .oauth2Login();
        
    }
}
```
