### DISCUSSION TITLE
Machine authentication with DEX having issues

### DISCUSSION THREAD

**Discussion by HeshaniSingtel** [dexidp/dex#3791] [Q&A]
I have dex and I use keycloak as my IDP. I'm trying to enable token exchange for a cli user. I'm able to retrieve a token from token endpoint. 

Dex config
------------
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://localhost:31328/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
      tokenExchange:
        allowTokenExchange: true
        allowedSubjects: ["test_client", "kubeflow-oidc-authservice"]
    enablePasswordDB: false
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/oauth2/callback"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
    - id: 'test_client'
      name: 'DEX Machine Login'
      secret: 'secret'
      redirectURI: http://localhost:31328/dex/callback
      public: true
    connectors:
    - type: oidc
      id: keycloak
      name: keycloak
      config:
        issuer: $CONNECTOR_ISSUER_URL
        clientID: $CONNECTOR_CLIENT_ID
        clientSecret: $CONNECTOR_CLIENT_SECRET
        redirectURI: http://localhost:31328/dex/callback
        scopes:
        - openid
        - profile
        - email
        - offline_access
        insecureSkipEmailVerified: true
        insecureSkipVerify: true
        insecureEnableGroups: true
        #insecureSkipVerify: true
        userIDKey: email
        userNameKey: email
    - type: oidc
      id: dex
      name: dex
      config:
        issuer: http://localhost:31328/dex
        clientID: $CONNECTOR_CLIENT_ID
        clientSecret: $CONNECTOR_CLIENT_SECRET
        redirectURI: http://localhost:31328/dex/callback
        scopes:
          - openid
          - profile
          - email
          - offline_access
        insecureSkipEmailVerified: true
        insecureSkipVerify: true
        insecureEnableGroups: true
        userIDKey: email
        userNameKey: email
```

Then I request id token from keycloak and use this id token to retrieve dex token. 

Token request
--------
<img width="726" alt="image" src="https://github.com/user-attachments/assets/782df151-6eb9-422e-8bbf-e83daba64f86">

And when I use this retrieved token as Bearer token, it does not get authenticated, it redirects me to the login page. 

I could not find any solution for this. Anyone else had the same issue and got it resolved?
