### DISCUSSION TITLE
Error when deploying Dex with ldap - Not Found Invalid client_id ("").

### DISCUSSION THREAD

**Discussion by papos8** [dexidp/dex#3813] [Q&A]
Hi, 

I am currently trying to deploy Dex with ldap connector, but I am facing the issue below when trying to access Dex on browser (Microsoft Edge).

![{EBEA1534-973F-490D-9DC6-69AD7329AF3A}](https://github.com/user-attachments/assets/034b6f73-386d-45a5-b610-eaa40f349a4f)

When accessing Dex from within the cluster, everything seems to work fine. Running _curl http://\<service\>/api/dex/auth_ from a test container returns the html response for the log in page for Dex. However, when exposing Dex through ingress and accessing it from a browser, I get the error shown in the screenshot above: _Not Found Invalid client_id ("")._.

What is this client id refer to? As per my understanding, configuring a client id is not necessary in the config section of Dex's configuration (like clientID for Microsoft Connector for example) and the client id doesn't refer to the static client I create. And even if I specify some value for client id, the error always returns _client_id("")_.

Logs from Dex show the error below:
![{DA561AAC-3D59-4736-91B4-DD3989951089}](https://github.com/user-attachments/assets/f6446a55-da11-4426-8fcc-d97acbe4de44)

Dex configuration below:

```
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: dex-cm
      namespace: dex
    data:
      config.yaml: |
        issuer: https://<endpoint>/api/dex
        web:
          http: 0.0.0.0:5556
        storage:
          type: memory
        connectors:
          - type: ldap
            name: ActiveDirectory
            id: ad
            config:
              redirectURIs: https://<endpoint>/callback
              host: <ldap_endpoint>
              insecureNoSSL: true
              insecureSkipVerify: true
              bindDN: <bindDN>
              bindPW: <bindPW>
              userSearch:
                  baseDN: <baseDN>
                  username: mail
                  filter: <filter>
                  idAttr: DN
                  emailAttr: mail
                  nameAttr: name
              groupSearch:
                  baseDN: <baseDN>
                  userMatchers:
                    - userAttr: DN
                      groupAttr: member
                  # Represents group name.
                  nameAttr: name
       staticClients:
                - id: kubernetes
                  name: kubernetes
                  secret: <secret>
                  redirectURIs:
                    - "http://localhost:8000"
```

I would appreciate some guidance on this.
