### DISCUSSION TITLE
Authentication for Machines

### DISCUSSION THREAD

**Discussion by marcelo-modolo** [dexidp/dex#4002] [Q&A]
Hi!
I read the documentation and the example in Authentication for Machines for Github but I would like to authenticate using an Enterprise Application in Azure AD, I made several attempts without success.

After setting up the coenctor, getting the token from Azure AD, I get the following error when trying to get the token from Dex:
`{"level":"error","msg":"failed to verify subject token: oidc: error loading userinfo: 400 Bad Request: ","time":"2025-02-21T22:24:06Z"}`

The connector configuration excerpt is below
```
connectors:
  - type: oidc
    id: azure-entra-id
    name: azure-entra-id
    config:
      issuer: https://sts.windows.net/{tenant_id}/
      scopes:
        - openid
        - profile
      userNameKey: sub
staticClients:
  - name: My App
    id: myapp
    secret: myapp
    public: true

```
I searched but couldn't find a configuration example for Azure AD
