### ISSUE TITLE
config: all sensitive fields should be configurable through a file or env var

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#1099]
Spun out of https://github.com/coreos/dex/issues/968 and to address https://github.com/coreos/dex/pull/943

Currently we let parts of dex config reference environment variables:

```yaml
storage:
- type: postgres
  config:
    password: $PASSWORD
```

We restrict this to storage and connectors since '$' can show up in things like bcrypt hashes. There have been additional request to add this to other parts of the config https://github.com/coreos/dex/pull/943. I'd like to propose we stop doing this.

Overall this is really bad since it lets the environment inject arbitrary bytes directly into the config. You could put an entire YAML object in that environment variable and it'd replace the environment variable reference. This is both hacky and prevents other tools from sanely parsing dex's config (https://github.com/coreos/dex/issues/968).

Add additional typed fields to sensitive config fields which let them be filled in by a file or env var explicitly. I should be able to configure a password like:

```yaml
staticPasswords:
- email: john.doe@example.com
  username: john
  hashFromFile: /var/run/dex/john-bcrypt-hash
- email: jane.doe@coreos.com
  username: jane
  hashFromEnv: JANE_BCRYPT_HASH
```

**Comment by jungziege** [comment]
Agreed this is a cleaner approach. How do you plan to handle backwards compatibility? Or do you plan to continue to allow expansion where it exists now.

**Comment by ericchiang** [comment]
> Agreed this is a cleaner approach. How do you plan to handle backwards compatibility? Or do you plan to continue to allow expansion where it exists now.

* Don't add new env var expansion logic.
* Continue to accept the literal values e.g. `hash`
* Add new optional fields like `hashFromFile` and `hashFromEnv`

Or we could do something like

```yaml
- email: john.doe@exapmle.com
  username: john
  password:
    file: /var/run/dex/john-bcrypt-hash
- email: jane.doe@example.com
  username: jane
  password:
    env: JANE_PASSWORD
```

Either way, we'll continue to be backward compatible. New fields will be optional.

**Comment by dnascimento** [comment]
Any updates?

**Comment by dafelipe130** [comment]
+1'ing here as well. I'm coming from #1158 and I could not put the identity configmap to source control with this still lingering around

**Comment by AlexMorreale** [comment]
would love this feature! :+1:

**Comment by SongGithub** [comment]
please, please, push this forward. I would love to see this feature got released soon. 

Currently there is so much pain to setup init container in k8s just to set the clinet secret without exposing it in our source code repo.

**Comment by captncraig** [comment]
as a workaround, I made a little script that I mount in my container and run as the command. All it does is run `sed` to rewrite the config file to a memory volume, then launch dex as normally. Its a bit of a hack, but it lets me load client secrets from kubernetes secrets via environment variables, which is all I wanted.

**Comment by krishnadurai** [comment]
@ericchiang I've implemented `hashFromEnv` for staticPasswords configuration as a starting point for this issue.
Could you please take a look at it?

**Comment by paul-theorem** [comment]
Also appears that static client secrets can't be ref'd from env vars.  My example would be: 
```    staticClients:
    - id: kubelogin
      redirectURIs:
      - http://localhost:28000
      name: 'kubelogin'
      secret: $KUBELOGIN_SECRET```

dex does not resolve the env var.  the dex config yaml will find its way into our git repo - and we'd prefer to put no secrets at all into source control.  I'd love to reference it from a kube secret resolved from an env var.

**Comment by sagikazarmark** [comment]
Personally, I'm not a huge fan of the `xyzFromEnv` style config. It complicates the config file itself, complicates config loading a LOT, makes it harder to test, etc.

I'd probably prefer some sort of config templating solution. For example, adding [dockerize](https://github.com/jwilder/dockerize) to the docker image would allow users to evaluate a config template and fill in certain values from environment variables when the container starts.

The same can be done with consul template.

I know it writes the resulting config file to ephemeral storage, but anyone who has access to the node filesystem can easily enter containers and check the environment variables as well.

**Comment by justinas-b** [comment]
+1

**Comment by Kampe** [comment]
+1

**Comment by damian-keska-f** [comment]
That would simplify usage with e.g. https://github.com/kubernetes-sigs/secrets-store-csi-driver

**Comment by benjamin-bergia** [comment]
Is there any update on this?

Dex is barely usable on kubernetes as it is right now. The only workaround I found is to store the whole config as a secret.

**Comment by nabokihms** [comment]
@benjamin-bergia starting from the version v2.28.0 Dex official docker image uses [complete](https://docs.gomplate.ca/) to render the config before execution.

Thus, it is possible to utilize env variables in the config like this 
https://github.com/dexidp/dex/blob/20e2e429b34086bc4ffbfbbae888f644ca1f1377/config.docker.yaml#L20

**Comment by benjamin-bergia** [comment]
@nabokihms Perfect! Thank you

**Comment by sagikazarmark** [comment]
Under the hood, Dex still uses a config file generated by gomplate. gomplate only makes operations easier (ie. you don't have to add sensitive values to install manifests), but it still gets written to the container filesystem.

**Comment by pinpox** [comment]
> written to the container filesystem.

Yes, but my question is if it works without docker aswell? I'm running
```
dex serve /run/dex/config.yaml
```
with `config.yaml` containing:
```yaml
staticClients:
- id: forum-app
  name: forum-app
  redirectURIs:
  - http://myhost.tld/authenticate
  secret: '{{ .Env.CLIENT_SECRET_RUST_FORUM }}'
  ```
  But the secret is not set correctly

**Comment by pinpox** [comment]
Okay, i found the solution: You can use `secretEnv` like this:
```yaml
staticClients:
- id: forum-app
  name: forum-app
  redirectURIs:
  - http://myhost.tld/authenticate
  secretEnv: 'CLIENT_SECRET_RUST_FORUM' # Variable name without the leading $
  ```
  This should be documented better, I had to search a lot to find this in [this issue](https://github.com/dexidp/dex/pull/1664)

**Comment by dermicus-miclip** [comment]
Bit flabbergasted that this is not solved. I mean, 2017! This issue makes it really annoying to use static config in combination with k8s. Why is this not getting some more love?

**Comment by sagikazarmark** [comment]
There is a reasonably good solution provided that allows you to use environment variables for your configuration explained above.

The reason why we haven't done anything more (ie. implementing this inside Dex) is because

a) we believe this is good enough and most people seem to agree
b) configuration needs some larger revamps and we may not want to commit to a solution that we would break later

**Comment by dermicus-miclip** [comment]
@sagikazarmark, I did not yet understand enough of exactly how the solution was supposed to work. But all seems to work now indeed :). Can't this ticket be closed then, as it is probably only confusing people getting started with dex.

**Comment by dharmil** [comment]
For people stumbling upon this issue, this is how you can configure Dex helm chart to use secrets for connectors and static clients:
```yaml
  connectors:
    - type: gitlab
      id: gitlab
      name: GitLab
      config:
        baseURL: https://gitlab.com
        clientID: '{{`{{ .Env.CLIENT_ID }}`}}'
        clientSecret: '{{`{{ .Env.CLIENT_SECRET }}`}}'
        redirectURI: http://{{ .Values.spec.dexHostName }}/callback
        getGroupsPermission: true

  staticClients:
    - id: controller-argocd-dex
      name: ArgoCD Client
      redirectURIs:
      - "http://argocd.domain.tld/auth/callback"
      secret: '{{`{{ .Env.OIDC_DEX_ARGO_CLIENT_SECRET }}`}}'
      scopes: {{ .Values.spec.defaultScopesToRequest }}
```

We need to use an expression like <mark>{{`{{ .Env.CLIENT_ID }}`}}</mark> in the helm chart so that the config.yaml gets an expression like `{{ .Env.CLIENT_ID }}` which would be interpreted by gomplate/Dex. The generated config file (with the values substituted) can, atleast in the current image, be viewed at /tmp/dex.config.yaml-* in the container/pod.
