### ISSUE TITLE
[Bitbucket] Bitbucket connector or generic oauth2 connector?

### ISSUE THREAD

**Issue by whereisaaron** [dexidp/dex#1179]
Back in v1 there was a [bitbucket connector](https://github.com/coreos/dex/blob/eb6dceadfd98ea786bce887502f5a74d8b49a256/connector/connector_bitbucket.go) for `dex`. It was removed for v2. Neither is their a generic oauth2 connector that could be used with bitbucket.org, and I don't think the `oidc` connector can be used?

Is there is any current support and ideally an example for using `bitbucket.org` with `dex`?

**Comment by whereisaaron** [comment]
I have Google working fine via the OIDC connector, and I assume, since this is no bitbucket-specific connector any more (was removed for dex v2), that OIDC would work for bitbucket.org?

Their OAuth2 information is [here]([url](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html)), is there OAuth2 implementation not sufficient for an OIDC flow?

This configuration below loads but them reports a 404 when connecting:
```
connectors:
  # Bitbucket Settings -> 'OAuth' -> 'Add OAuth consumer', add callback URL
  - type: oidc
    id: bitbucket
    name: Bitbucket
    config:
      issuer: https://bitbucket.org/site/oauth2/authorize
      clientID: $BITBUCKET_KEY
      clientSecret: $BITBUCKET_SECRET
      redirectURI: https://dex.example.com/callback
```

Adding the application at the bitbucket.org end seems clear enough:
![bitbucket-oauth2-consumer](https://user-images.githubusercontent.com/1109585/36291914-23d9511e-129c-11e8-8b4f-61791865e74f.png)

And if I visit this URL:
```
https://bitbucket.org/site/oauth2/authorize?client_id=$BITBUCKET_KEY&response_type=code
```
Then I get the screen you would expect:
![bitbucket-oauth2-auth](https://user-images.githubusercontent.com/1109585/36291992-b45f91a8-129c-11e8-8162-161b7237c00b.png)

If you authorize you get sent to the callback address with a code
```
https://dex.example.com/callback?code=abcedfg12345678
```
and I gather you swap that code for a token from `https://bitbucket.org/site/oauth2/access_token` via
```
$ curl -X POST -u "client_id:secret" \
  https://bitbucket.org/site/oauth2/access_token \
  -d grant_type=authorization_code -d code={code}
```
Can Dex support Bitbucket like this, or the custom connector needed again?
