### ISSUE TITLE
invalid bearer token, crypto/rsa: verification error

### ISSUE THREAD

**Issue by austbot** [dexidp/dex#1215]
I'm getting an error I cant find any other material on.
We have a Kops provisioned Kubernetes 1.9.4 cluster with Dex installed.
Okta is installed in Dex as a connector.
Using the example app I am able get a token using the Okta auth strategy. But when I try to use the token I get this in the ApiServer logs and literally nothing else.

`Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]`

Here is the API Server config using the kops yaml:
  ```
oidcIssuerURL: https://blahblahblah.com
oidcClientID: okta
oidcUsernameClaim: email
oidcGroupsClaim: groups
oidcCAFile: /etc/kubernetes/ssl/DigiCertCA.crt
```
We are using a public url for dex that is looping back into our cluster, the endpoint is an AWS ELB with an AWS provisioned cert. The Digicert CA is installed and there are no SSL issues reaching the dex server at least from outside. And Kubernetes is not reporting any errors hitting the oidc provider.

Here is the Dex config:
```
config.yaml: |
    issuer: https://blahblahblah.com
    storage:
      type: kubernetes
      config:
        inCluster: true
    logger:
      level: debug
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    oauth2:
      skipApprovalScreen: false
    staticClients:
    - id: okta
      redirectURIs:
      - 'http://127.0.0.1:5555/callback'
      name: 'Example App'
      admin: true
      secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    connectors:
    - type: saml
      id: saml
      name: Okta
      config:
        ssoIssuer: http://www.okta.com/exke8lzz0vbR268cm0h7
        ssoURL: https://https://blahblahblah.oktapreview.com/app/https://blahblahblahsandbox_kube/nonsense/sso/saml
        ca: /etc/dex-saml/okta.cert
        insecureSkipSignatureValidation: true
        redirectURI: https://blahblahblah/callback
        usernameAttr: name
        emailAttr: email
        groupsAttr: groups
        nameIDPolicyFormat: emailAddress
```

At first we were using the same SSL certs that were on the load balancer for dex, but I then switched to the certs provided by the ./gencerts.sh in examples/k8s. I wasn't sure if the tls.key was used in anyway for the jwt. I didn't think so but I am grasping at straws. 

Again the error message only says `Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, crypto/rsa: verification error]]`
I doesn't give any more reasons like the other issues I have seen posted with crypto/rsa errors.

For reference here is the full api server config:
```
address: 127.0.0.1
  admissionControl:
  - Initializers
  - NamespaceLifecycle
  - LimitRanger
  - ServiceAccount
  - PersistentVolumeLabel
  - DefaultStorageClass
  - DefaultTolerationSeconds
  - NodeRestriction
  - Priority
  - DenyEscalatingExec
  - ResourceQuota
  allowPrivileged: true
  anonymousAuth: false
  apiServerCount: 3
  authorizationMode: RBAC
  cloudProvider: aws
  etcdServers:
  - http://127.0.0.1:4001
  etcdServersOverrides:
  - /events#http://127.0.0.1:4002
  image: gcr.io/google_containers/kube-apiserver:v1.9.4
  insecurePort: 8080
  kubeletPreferredAddressTypes:
  - InternalIP
  - Hostname
  - ExternalIP
  logLevel: 2
  requestheaderAllowedNames:
  - aggregator
  requestheaderExtraHeaderPrefixes:
  - X-Remote-Extra-
  requestheaderGroupHeaders:
  - X-Remote-Group
  requestheaderUsernameHeaders:
  - X-Remote-User
  securePort: 443
  serviceClusterIPRange: 100.64.0.0/13
  storageBackend: etcd2
  oidcIssuerURL: https://blahblahblah.com
oidcClientID: okta
oidcUsernameClaim: email
oidcGroupsClaim: groups
oidcCAFile: /etc/kubernetes/ssl/DigiCertCA.crt
```

Any help is appreciated.
