### ISSUE TITLE
Issues integrating with Azure AD

### ISSUE THREAD

**Issue by drshade** [dexidp/dex#1306]
I have followed the microsoft connector readme, and have the following very simple connector configuration for dex:
```
  - type: microsoft
    id: microsoft
    name: Microsoft
    config:
      clientID: <snip>
      clientSecret: <snip>
      redirectURI: https://dex.mydomain.com/callback
```

I've registered my app on https://apps.dev.microsoft.com, added the Directory.Read.All delegated permission, and also updated the application manifest to include the replyUrl back to my dex ingress.

My current issue seems to be that I cannot get the admin_consent piece working. When I hit the url 
```
https://login.microsoftonline.com/<snip>/adminconsent?client_id=<snip>
```

I go through the login with Microsoft, receive the Accept permissions page, but when hitting Accept, it redirects to my dex instance, but dex throws the following error back to the browser:
"Bad Request User session error."

The URL that Microsoft is redirecting to is:
```
https://dex.mydomain.com/callback?admin_consent=True&tenant=<snip>
```

What am I missing? I've got logging set to debug, but nothing appears in dex's logs unfortunately. 

I am running quay.io/dexidp/dex:v2.11.0

Any assistance really appreciated.

All the best,
Tom

**Comment by praveendhac** [comment]
Did you configure "Reply URLs" to https://dex.mydomain.com/callback for cliend_id on AzureAD?
Are you able to access https://dex.mydomain.com/.well-known/openid-configuration?
This works for me
```
  connectors:
  - type: microsoft
    id: microsoft
    name: Microsoft
    config:
      clientID: <REDACTED>
      clientSecret: <REDACTED>
      redirectURI: https://authn.ingress.dex.pd.com/callback
      tenant: <REDACTED>```

What error are you getting when https://login.microsoftonline.com/<snip>/adminconsent?client_id=<snip> is accessed.

**Comment by srenatus** [comment]
It's been a month now... Is this still bothering you or can we clean this up? 😃

**Comment by srenatus** [comment]
Looks like this can be cleaned up. Feel free to re-open.

**Comment by RichardLindhout** [comment]
We have the exact same problem now.

**Comment by RichardLindhout** [comment]
```
    connectors:
    - type: microsoft
      id: microsoft
      name: Microsoft
      config:
        clientID: <REDACTED>
        clientSecret: <REDACTED>
        redirectURI: https://accounts.<REDACTED>.com/accounts/callback
```
