### ISSUE TITLE
Docker: container exit immediately after create

### ISSUE THREAD

**Issue by tuyenpm9** [dexidp/dex#1326]
I have this `docker-compose.yml`

```
<..>
  dex:
    image: quay.io/dexidp/dex:v2.12.0
    ports:
      - "5555:5555"
```

Dex container created sucessfully, but exited after creation.

`docker logs <dex-container-name>` gives:

```
dex Version: v2.12.0
Go Version: go1.10.2
Go OS/ARCH: linux amd64
```
I expect dex up and listen on port `5555`, did I miss something?
