### ISSUE TITLE
failed to initialize storage: failed to perform migrations

### ISSUE THREAD

**Issue by tuyenpm9** [dexidp/dex#1327]
I'm trying to setup dex to authen against ldap that also used by docker_auth to authen users. The idea is users authen against dex then delegate to private `registry` then registry query docker_auth to authen the second time, if good allow push/pull.

I don't know token generated by dex or docker_auth may conflict, have no idea.

But dex and docker_auth would use the same ldap database/structure to authen, that I suspect give me this error when trying to wake dex container up.

error:
```
docker logs docker-registry-dex_1
time="2018-10-23T13:24:57Z" level=info msg="config issuer: http://dex.example.com:5556/dex"
failed to initialize storage: failed to perform migrations: creating migration table: unable to open database file
```
```
vi docker-compose.yml
    build: ./dex
    ports:
      - "5555:5555"
```

Dockerfile
```
COPY examples/config.yml config.yaml

ENTRYPOINT ["dex"]

CMD ["serve", "config.yaml"]
```

config.yml
```
issuer: http://dex.example.com:5556/dex
storage:
  type: sqlite3
  config:
    file: examples/dex.db
web:
  http: dex.example.com:5556

connectors:
- type: ldap
  name: OpenLDAP
  id: ldap
  config:
    host: ldap.example.com:10389

    # No TLS for this setup.
    insecureNoSSL: true
```

Problem is even I stop docker_auth container, I still got above error.
