### ISSUE TITLE
env var not interpolated

### ISSUE THREAD

**Issue by SongGithub** [dexidp/dex#1330]
In the [official example](https://github.com/dexidp/dex/blob/v2.10.0/examples/k8s/dex.yaml), clearly it is trying to set an ENV VAR `GITHUB_CLIENT_SECRET` from a k8s secret, then use it in config map as `$GITHUB_CLIENT_SECRET`, hoping it could interpolate the value of that ENV VAR.

Unfortunately, at v2.10.0, it does not. We have tried many times. 

This bug makes it more complicated than necessary for us to inject a k8s secret, which is using a init-container running Gomplate to generate the configmap dex wants to use with secret inside.

That is one step from being great module! Please make a fix for this issue, thanks!

**Comment by srenatus** [comment]
The `staticClients` config is not the same as a connector config. It does
not do any env expansion, unfortunately...

**Comment by srenatus** [comment]
[Searching](https://github.com/dexidp/dex/search?q=staticClients+env&type=Issues) yields #1099. What do you think about that proposal, @SongGithub? 😃

**Comment by SongGithub** [comment]
let me clarify the proposal, is that like following 
```
    staticClients:
      - id: grafana
        redirectURIs:
          - 'https://demo/oauth/callback'
        name: 'foobar'
        secret: $BCRYPT_HASH_OF_OIDC_SECRET
    enablePasswordDB: false
```
