### ISSUE TITLE
How do I get example app to ignore ssl validation

### ISSUE THREAD

**Issue by sgir** [dexidp/dex#1331]
I am trying to get Dex working in localhost with https. I am able to access the Dex Endpoints. 

But, When I make a request from the example-app which was working with http before, I get

`error: Failed to query provider "https://saml-dex-lor.com:5556/dex": Get https://saml-dex-lor.com:5556/dex/.well-known/openid-configuration: x509: certificate signed by unknown authority`

Some more info : 

I am starting the client like so 

`$ ./bin/example-app --issuer "https://saml-dex-lor.com:5556/dex" --tls-cert  examples/domain_crt.pem --tls-key examples/domain_key.pem`

I generated the certs as follows and added to the configuration. 
`openssl req -newkey rsa:2048 -nodes -keyout domain_key.pem -x509 -days 365 -out domain_crt.pem`

My config-dev.yaml File: 
```
# The base path of dex and the external name of the OpenID Connect service.
# This is the canonical URL that all clients MUST use to refer to dex. If a
# path is provided, dex's HTTP service will listen at a non-root URL.
issuer: https://saml-dex-lor.com:5556/dex

# The storage configuration determines where dex stores its state. Supported
# options include SQL flavors and Kubernetes third party resources.
#
# See the storage document at Documentation/storage.md for further information.
storage:
  type: sqlite3
  config:
    file: examples/dex.db

# Configuration for the HTTP endpoints.
web:
  # http: 0.0.0.0:5554
  # Uncomment for HTTPS options.
  https: 0.0.0.0:5556
  tlsCert: examples/domain_crt.pem
  tlsKey: examples/domain_key.pem

# Configuration for telemetry
telemetry:
  http: 0.0.0.0:5558

# Uncomment this block to enable the gRPC API. This values MUST be different
# from the HTTP endpoints.
# grpc:
#   addr: 127.0.0.1:5557
#  tlsCert: examples/grpc-client/server.crt
#  tlsKey: examples/grpc-client/server.key
#  tlsClientCA: /etc/dex/client.crt

# Uncomment this block to enable configuration for the expiration time durations.
# expiry:
#   signingKeys: "6h"
#   idTokens: "24h"

# Options for controlling the logger.
# logger:
  level: "debug"
  format: "json" # can also be "json"

# Uncomment this block to control which response types dex supports. For example
# the following response types enable the implicit flow for web-only clients.
# Defaults to ["code"], the code flow.
# oauth2:
#   responseTypes: ["code", "token", "id_token"]

# Instead of reading from an external storage, use this list of clients.
#
# If this option isn't chosen clients may be added through the gRPC API.
# First, client details should be present in the dex configuration. For example, we could register an app with dex with the following section:
staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

connectors:
- type: saml
  # Required field for connector id.
  id: saml
  # Required field for connector name.
  name: SAML
  config:
    # SSO URL used for POST value.
    ssoURL:     ssoIssuer: https://idp.url.ondemand.com/saml2/idp/sso/idp.url.ondemand.com

    # CA to use when validating the signature of the SAML response.
    # ca: examples/ycloudidp.pem

    # Dex's callback URL.
    #
    # If the response assertion status value contains a Destination element, it
    # must match this value exactly.
    #
    # This is also used as the expected audience for AudienceRestriction elements
    # if entityIssuer isn't specified.
    # redirectURI: https://dex.example.com/callback
    redirectURI: http://saml-dex-lor.com:5556/dex/callback

    # Name of attributes in the returned assertions to map to ID token claims.
    usernameAttr: first_name
    emailAttr: mail
    groupsAttr: groups # optional

    # CA's can also be provided inline as a base64'd blob.
    #
    # caData: ( RAW base64'd PEM encoded CA )
    caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHakNDQWdLZ0F3SUJBUUlHQVdCeklTMzN....

    # To skip signature validation, uncomment the following field. This should
    # only be used during testing and may be removed in the future.
    #
    # insecureSkipSignatureValidation: true

    # Optional: Manually specify dex's Issuer value.
    #
    # When provided dex will include this as the Issuer value during AuthnRequest.
    # It will also override the redirectURI as the required audience when evaluating
    # AudienceRestriction elements in the response.
    # entityIssuer: https://dex.example.com/callback
    entityIssuer: urn:saml-dex-lor

    # Optional: Issuer value expected in the SAML response.
    ssoIssuer: https://idp.url.ondemand.com/saml2/idp/sso/idp.url.ondemand.com

    # Optional: Delimiter for splitting groups returned as a single string.
    #
    # By default, multiple groups are assumed to be represented as multiple
    # attributes with the same name.
    #
    # If "groupsDelim" is provided groups are assumed to be represented as a
    # single attribute and the delimiter is used to split the attribute's value
    # into multiple groups.
    groupsDelim: ", "

    # Optional: Requested format of the NameID.
    #
    # The NameID value is is mapped to the user ID of the user. This can be an
    # abbreviated form of the full URI with just the last component. For example,
    # if this value is set to "emailAddress" the format will resolve to:
    #
    #     urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
    #
    # If no value is specified, this value defaults to:
    #
    #     urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
    #
    nameIDPolicyFormat: unspecified

# Let dex keep a list of passwords which can be used to login to dex.
# enablePasswordDB: true

# A static list of passwords to login the end user. By identifying here, dex
# won't look in its underlying storage for passwords.
#
# If this option isn't chosen users may be added through the gRPC API.
# staticPasswords:
# - email: "admin@example.com"
#   # bcrypt hash of the string "password"
#   hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
#   username: "admin"
#   userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

```

note: localhost is mapped to saml-dex-lor.com in the host file. 

How can I fix this error? Many thanks in advance!
