### ISSUE TITLE
Help authenticating with Salesforce

### ISSUE THREAD

**Issue by pwhittlesea** [dexidp/dex#1360]
```
dex Version: 5f054fcf2e1aac5278a9b87bf41725f6c9c78efe
Go Version: go1.10
Go OS/ARCH: linux amd64
```

I am trying to get dex to authenticate with the Salesforce which is advertised in the README.

I have followed the getting started guide and have the following configuration:
```yaml
issuer: http://localhost:5556/dex
storage:
  type: sqlite3
  config:
    file: examples/dex.db
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: "json"
staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
connectors:
- type: oidc
  id: salesforce
  name: Salesforce
  config:
    issuer: "https://login.salesforce.com"
    clientID: "<redacted>"
    clientSecret: "<redacted>"
    redirectURI: http://localhost:5556/dex/callback
```

in addition to configuring the OIDC connector I have had to reconfigure the IPs to be localhost instead of 127.0.0.1 due to restrictions on redirect URLs in Salseforce.

When authenticating I get past the page to allow the application to use my details and am then presented with a page showing the following:

```
Internal Server Error

Failed to authenticate: oidc: failed to get token: oauth2: cannot fetch token: 400 Bad Request Response: {"error":"invalid_request","error_description":"scope parameter not supported"}
```

and in the logs I get:

```json
{"level":"error","msg":"Failed to authenticate: oidc: failed to get token: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_request\",\"error_description\":\"scope parameter not supported\"}","time":"2018-11-26T09:00:22Z"}
```

Additionally I am running the example app using:
```sh
./bin/example-app --issuer http://localhost:5556/dex
```

Is there something I am missing with the configuration or is Salesforce not a valid OIDC endpoint?

Thanks in advance.
