### ISSUE TITLE
OIDC Azure invalid client secret

### ISSUE THREAD

**Issue by brondum** [dexidp/dex#1375]
Hi.

I am hitting my head against the wall with this issue, hope you have some insight.
I keep getting the error:

```
time="2018-12-17T13:53:17Z" level=error msg="Failed to authenticate: oidc: failed to get token: oauth2: cannot fetch token: 401 Unauthorized
Response: {\"error\":\"invalid_client\",\"error_description\":\"AADSTS*****: Error validating credentials. AADSTS*****: Invalid client secret is provided.\r\nTrace ID: *****\r\nCorrelation ID: *****\r\nTimestamp: 2018-12-17 13:53:17Z\",\"error_codes\":[70002,50012],\"timestamp\":\"2018-12-17 13:53:17Z\",\"trace_id\":\"*****\",\"correlation_id\":\"*****\"}"
```

I have tried with different secrets (created new ones). With them as env vars, i have tried url encoded them, i have tried in single quotes and in double quotes, and without any quotes at all.

My config is as follows:
```
# The base path of dex and the external name of the OpenID Connect service.
# This is the canonical URL that all clients MUST use to refer to dex. If a
# path is provided, dex's HTTP service will listen at a non-root URL.
issuer: https://localhost:5554/dex

# The storage configuration determines where dex stores its state. Supported
# options include SQL flavors and Kubernetes third party resources.
#
# See the storage document at Documentation/storage.md for further information.
storage:
  type: sqlite3
  config:
    file: dex.db

# Configuration for the HTTP endpoints.
web:
  http: 0.0.0.0:5556
  # Uncomment for HTTPS options.
  https: 0.0.0.0:5554
  tlsCert: <hidden>
  tlsKey: <hidden>

# Configuration for telemetry
telemetry:
  http: 0.0.0.0:5558

# Uncomment this block to enable the gRPC API. This values MUST be different
# from the HTTP endpoints.
# grpc:
#   addr: 127.0.0.1:5557
#  tlsCert: examples/grpc-client/server.crt
#  tlsKey: examples/grpc-client/server.key
#  tlsClientCA: /etc/dex/client.crt

# Uncomment this block to enable configuration for the expiration time durations.
# expiry:
#   signingKeys: "6h"
#   idTokens: "24h"

# Options for controlling the logger.
# logger:
#   level: "debug"
#   format: "text" # can also be "json"

# Uncomment this block to control which response types dex supports. For example
# the following response types enable the implicit flow for web-only clients.
# Defaults to ["code"], the code flow.
# oauth2:
#   responseTypes: ["code", "token", "id_token"]

# Instead of reading from an external storage, use this list of clients.
#
# If this option isn't chosen clients may be added through the gRPC API.
staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: <hidden>

- id: pbm-app
  redirectURIs:
  - 'https://localhost:8080/callback'
  name: 'Pbm App'
  secret: <hidden>

connectors:
- type: oidc
  id: azure
  name: Azure
  config:
    issuer: 'https://login.microsoftonline.com/<appid>/v2.0'
    # Connector config values starting with a "$" will read from the environment.
    clientID: <hidden>
    clientSecret: <hidden>
    redirectURI: 'https://localhost:5554/dex/callback'
```

Any insights in what i am doing wrong?
