### ISSUE TITLE
No Auth provider found for name "oidc"

### ISSUE THREAD

**Issue by Kydybets** [dexidp/dex#1401]
After implementation of Dex, and get config after verification with AD,
I copy->paste this config into my ~./kube/config file replace contextsand try to login.

My config look like this
```
- name: <username>
  user:
    auth-provider:
      config:
        client-id: login
        client-secret: <secret>
        id-token: <id-token>
        idp-issuer-url: https://dex.k8.example/dex
        refresh-token: <token.
      name: oidc
```
And get next message
```
error: No Auth provider found for name "oidc"
```
After that, I decide to delete auth-provider level and everything starts working like it should be.

I am not sure does this is a bug.
Would be nice if someone can take a look of this.
