### ISSUE TITLE
Support LDAP netgroups & nisNetgroupTriple values

### ISSUE THREAD

**Issue by rgazaryants** [dexidp/dex#1419]
I tried various combinations for searching nisNetgroup and nisNetgroupTriple to get group membership without luck. Don't think it's supported.

In our case, it would be something like:
```
groupSearch:
        baseDN: ou=Netgroups,dc=domain,dc=com
        filter: "(objectClass=nisNetgroup)"
        groupAttr: nisNetgroupTriple
        userAttr: uid
        nameAttr: cn
```

But nisNetgroupTriple entries look as such: `(,uid,)`
