### ISSUE TITLE
Not able to find group

### ISSUE THREAD

**Issue by anirvanr** [dexidp/dex#1450]
Hi,

Dex is not able to find group using search , see the error below

```
level=info msg="performing ldap search ou=groups,dc=example,dc=com sub (&(objectClass=posixGroup)(memberUid=john))" connector=LDAP
```
My dex config for groups
```
....
groupSearch:
  baseDN: ou=groups,dc=example,dc=com
  filter: "(objectClass=posixGroup)"
  userAttr: uid
  groupAttr: memberUid
  nameAttr: cn
```

My ldap config 
```
# groups, example.com
dn: ou=groups,dc=example,dc=com
objectClass: organizationalUnit
ou: groups

# administrators, groups, example.com
dn: cn=administrators,ou=groups,dc=example,dc=com
cn: administrators
objectClass: posixGroup
objectClass: top
gidNumber: 600
memberUid: john

# john, people, example.com
dn: uid=john,ou=people,dc=example,dc=com
uid: john
cn: john
givenName: john
sn: ray
mail: john.ray@example.com
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: top
loginShell: /bin/bash
uidNumber: 10002
gidNumber: 10000
homeDirectory: /home/john
```
Can you please help ?

Thanks
