### ISSUE TITLE
Invalid 'state' parameter provided: not found

### ISSUE THREAD

**Issue by acarsercan** [dexidp/dex#1466]
Hi,

Kubernetes 0.11.9
dex-2.16.0
dex-k8s-authenticator-v1.1.0

Trying to enable dex in my cluster to allow read-only access using github authentication

Enabling authenticator like so

```
dexK8sAuthenticator:
  port: 5555
  debug: true
  web_path_prefix: /
  #logoUrl: http://<path-to-your-logo.png>
  #tlsCert: /path/to/dex-client.crt
  #tlsKey: /path/to/dex-client.key
  clusters:
  - name: XXX-cluster
    short_description: "XXX"
    description: "Example Cluster Long Description..."
    client_secret: XXXX
    issuer: https://XXXX
    k8s_master_uri:XXXX
    client_id: XXXX
    redirect_uri: https://XXXXX/callback
    k8s_ca_uri: https://url-to-your-ca.crt
...
```

Enabling dex like so

```
config:
  issuer: https://XXXXXX
  connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: xxxxx
      clientSecret: xxxxx
      redirectURI: https://XXXX/callback
      orgs: 
      - name: XXXXXX
  staticClients:
  - id: XXXXX
    redirectURIs:
      - https://XXXXXcallback
    name: XXX
    secret: XXX
```

Once I click Github in authenticator UI, I get the following in the logs

 ```level=error msg="Invalid 'state' parameter provided: not found" ```

Not sure what to make of that
