### ISSUE TITLE
Active Directory Groups Not Being Pulled 

### ISSUE THREAD

**Issue by simonmacklin** [dexidp/dex#1483]
Hi 

Would anyone be able to point me in the right direction?

I have been trying to get DEX working with Active Directory.  Authentication works great but it will not pull the groups memberships of the user.

I have seen a couple of issues already created which did not resolve it for me.  This is the connector config I am using. 

```
- type: ldap
    name: AD
    id: ldap
    config:
      host: 10.0.0.21:636
      insecureNoSSL: false
      bindDN: CN=dex,**
      bindPW: *******
      insecureSkipVerify: true
      usernamePrompt: Username

      userSearch:
        baseDN: OU=Users,OU=*
        filter: "(objectClass=User)"
        username: samAccountName
        idAttr: DN
        emailAttr: mail
        nameAttr: cn

      groupSearch:
        baseDN: OU=Groups,* 
        #filter: "(objectClass=group)"
        userAttr: DN
        groupAttr: member
        nameAttr: name
```
I have removed and replace the OUs with * 

Thanks in advance
