### ISSUE TITLE
Documentation on how to customize web-app template

### ISSUE THREAD

**Issue by eohtake** [dexidp/dex#1525]
I'm trying to figure out how to customize my local install (logo, buttons, etc) and based on this documentation: https://github.com/dexidp/dex/blob/89e43c198b30fb1b43c9d49f3ab772ef88d8664d/Documentation/templates.md

Where exactly this piece of yaml should go? 

```
frontend:
  dir: /path/to/custom/web
  extra:
    tos_footer_link: "https://example.com/terms"
    client_logo_url: "../theme/client-logo.png"
    foo: "bar"
```
