### ISSUE TITLE
When would Issuer and web ever differ?

### ISSUE THREAD

**Issue by Joematpal** [dexidp/dex#1531]
```yaml
# The base path of dex and the external name of the OpenID Connect service.
# This is the canonical URL that all clients MUST use to refer to dex. If a
# path is provided, dex's HTTP service will listen at a non-root URL.
issuer: https://dex.example.com:32000
# Configuration for the HTTP endpoints.
web:
  http: 0.0.0.0:5556
```

In the basic example they are the same. However, in the k8s example they are different. What would the use case be for these to being different?
