### ISSUE TITLE
How to use the CRD's

### ISSUE THREAD

**Issue by Smana** [dexidp/dex#1606]
Hey folks,

I'm trying to use the CRD's to dynamically configure Dex.
I search for examples in the repository but I couldn't find anyone.
So I just tried to create the object by appending the configuration into the `spec` field of the object but that didn't work either.
example:
```
apiVersion: dex.coreos.com/v1
kind: OAuth2Client
metadata:
  name: myclient
spec:
  id: myclient
  name: "myclient"
  secret: "mysecret"
  redirectURIs:
    - http://localhost:5555/callback
```

Any help would be welcome.
