### ISSUE TITLE
Issues with Google OIDC configuration

### ISSUE THREAD

**Issue by Smana** [dexidp/dex#1611]
Hey everyone,

I'm using Dex in my current company for years now, using an LDAP connector. It works great.
Now I wanted to try the Google connector in order to use the same account in our GKE clusters and on-premises.

I managed to get and ID and Secret using google API and I configured the connector as follows
```
config:
  issuer: https://dex.domain.tld
  connectors:
    - type: oidc
      id: google
      name: Google
      config:
        issuer: https://accounts.google.com

        # Connector config values starting with a "$" will read from the environment.
        clientID: "myID.apps.googleusercontent.com"
        clientSecret: "mySecret"

        # Dex's issuer URL + "/callback"
        redirectURI: https://dex.domain.tld/callback

        hostedDomains:
          - domain.tld

        scopes:
          - profile
          - email
          - groups

  oauth2:
    alwaysShowLoginScreen: false
    skipApprovalScreen: true

  expiry:
    signingKeys: "6h"
    idTokens: "24h"

  staticClients:
    - id: client1
      name: "client1"
      secret: "clientSecret"
      redirectURIs:
        - http://localhost:5555/callback
```

And we make use of a home made client to perform the authentication that listens on localhost:5555 as you can see in the configuration above.
However when I try I get a "redirect_uri_mismatch" error

When I look to the nginx controller logs I can see:
```
188.65.x.x - 188.65.x.x - - [25/Dec/2019:08:46:12 +0000] "GET /auth/google?req=ziynqykv3q7tecg63is3k2szw HTTP/2.0" 302 362 "https://dex.domain.tld/auth?client_id=client1&redirect_uri=http%3A%2F%2Flocalhost%3A5555%2Fcallback&response_type=code&scope=groups+openid+profile+email+offline_access&state=login" "Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0" 44 0.020 [smana-dex-smana-32000] 10.174.15.202:5556 362 0.020 302
```

I probably did something wrong or misunderstood something. Any help would be welcome.

Thank you,
Smana
