### ISSUE TITLE
config: No way to escape $ in connector-config

### ISSUE THREAD

**Issue by msiebuhr** [dexidp/dex#1619]
I've been playing with adding a SQL (Posgres) connector, as we have internal users there. To make that re-usable, I figured the query should be configurable, say:

```yaml
connectors:
- type: sql
  id: authdb
  name: Internal Auth DB 
  config:
    connection: host=localhost password=test ...
    query: "SELECT userId, ... WHERE username = $1 AND pwhash = crypt($2, pwhash)"
    groupQuery: ...
```

But the SQL placeholders (`$1` and `$2`) vanish because of the environment-expansion done in `cmd/dex/config.go`:

```go
connConfig := f()
if len(conn.Config) != 0 {
	data := []byte(os.ExpandEnv(string(conn.Config))) // - Here
	if err := json.Unmarshal(data, connConfig); err != nil {
		return fmt.Errorf("parse connector config: %v", err)
	}
}
```
I can see there's some vaguely related work going on in https://github.com/dexidp/dex/issues/1099

This could be fixed by forking `os.ExpandEnv` to leave unknown env's alone (which would break if anyone set `1=foo`) OR break out the reflection-package, walk the config-tree and check every string-key for starting with a `$` and matching some env name.
