### ISSUE TITLE
error unmarshaling JSON: unknown connector type "openshift"

### ISSUE THREAD

**Issue by cybrwshl** [dexidp/dex#1642]
We're trying to install dex with the default helm chart in openshift 4.2.
But unfortunately we get the following error message from dex:
`error parse config file /etc/dex/cfg/config.yaml: error unmarshaling JSON: unknown connector type "openshift"`

The config file looks like this:
```yaml
issuer: http://dex.io:8080
storage:
  config:
    inCluster: true
  type: kubernetes
logger:
  level: debug
web:
  http: 0.0.0.0:5556
connectors:
- config:
    clientID: kubeapps
    clientSecret: SECRET
    groups:
    - ocp_devs
    - ocp_admins
    insecureCA: true
    issuer: https://api.example.com:6443
    redirectURI: http://127.0.0.1:5556/dex/
    rootCA: /etc/ssl/openshift.pem
  id: openshift
  name: OpenShift
  type: openshift
oauth2: 
  alwaysShowLoginScreen: false
  skipApprovalScreen: true
enablePasswordDB: true
```
