### ISSUE TITLE
error: You must be logged in to the server

### ISSUE THREAD

**Issue by schizoid90** [dexidp/dex#1647]
Dex version: 2.21.0
Gangway version: 3.3.0
Kubernetes version: 1.16.1

I have Dex and Gangway running in Kubernetes. I generate a kubeconf file through the web UI but when I try to authenticate with the Kubernetes API I get an "unauthorized" error

**Gangway Configfile**

```
apiServerURL: https://k8sapi-prod.domain.lan:6443
audience: https://dex.domain.lan/userinfo
authorizeURL: https://dex.domain.lan/auth
clientID: ldapauth
clientSecret: aoQ9JKU0KhNsz2V
clusterName: k8s
emailClaim: email
port: 8080
redirectURL: https://gangway.domain.lan/callback
scopes:
- openid
- profile
- email
- offline_access
sessionKey: *********
tokenURL: https://dex.domain.lan/token
usernameClaim: email
```

**Dex config**

```
issuer: https://dex.domain.lan
storage:
  config:
    inCluster: true
  type: kubernetes
logger:
  level: debug
web:
  http: 0.0.0.0:5556
connectors:
- config:
    bindDN: CN=k8s-ro,OU=Service Accounts,OU=Kubernetes,OU=Services,DC=domain,DC=lan
    bindPW: ************
    clientID: ldapauth
    clientSecret: aoQ9JKU0KhNsz2V
    groupSearch:
      baseDN: OU=Security Groups,OU=Kubernetes,OU=Services,DC=domain,DC=lan
      filter: (objectClass=group)
      groupAttr: member
      nameAttr: name
      userAttr: SamAccountName
    host: domain.lan:636
    insecureNoSSL: false
    insecureSkipVerify: true
    userSearch:
      baseDN: DC=domain,DC=lan
      emailAttr: mail
      filter: (objectClass=person)
      idAttr: DN
      nameAttr: name
      username: SamAccountName
    usernamePrompt: Username
  id: ldap
  name: LDAP
  type: ldap
oauth2:
  alwaysShowLoginScreen: false
  skipApprovalScreen: true
staticClients:
- id: ldapauth
  name: oidc-auth-client
  redirectURIs:
  - https://gangway.domain.lan/callback
  secret: aoQ9JKU0KhNsz2V
```

**Kubeconfig**
Generated through Gangway/Dex and saved locally

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZ4ekNDQTYrZ0F3SUJBZ0lVUDYxa2k3d2NOU1VkdTlTamhWNU8rUkZJeTFvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2N6RUxNQWtHQTFVRUJoTUNSMEl4RGpBTUJnTlZCQWdNQlU1dmRIUnpNUk13RVFZRFZRUUhEQXBPYjNSMAphVzVuYUdGdE1SRXdEd1lEVlFRS0RBaEVja1p2YzNSbGNqRVBNQTBHQTFVRUN3d0dSR1YyVDNCek1Sc3dHUVlEClZRUUREQkpvWld4dExtUnlMV1p2YzNSbGNpNXNZVzR3SGhjTk1Ua3hNakV6TURjME5EVXdXaGNOTWpBeE1qRXkKTURjME5EVXdXakJ6TVFzd0NRWURWUVFHRXdKSFFqRU9NQXdHQTFVRUNBd0ZUbTkwZEhNeEV6QVJCZ05WQkFjTQpDazV2ZEhScGJtZG9ZVzB4RVRBUEJnTlZCQW9NQ0VSeVJtOXpkR1Z5TVE4d0RRWURWUVFMREFaRVpYWlBjSE14Ckd6QVpCZ05WQkFNTUVtaGxiRzB1WkhJdFptOXpkR1Z5TG14aGJqQ0NBaUl3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dJUEFEQ0NBZ29DZ2dJQkFKNCtBTytZVXpRU3BjaFN1azFURlUycEJteDhVa1lyNDk4UWVQUWpQNjd1dHRFaApTWUFTdVRhV3FJNkhSbWVrVVRueDZ1eDh2YVAyVEVOM09obEZSeFlpMzR2MDVFQ1F1YXBOdHNiOFVTenl2SHR0CnA1dnkrVTVkNWFpTmlUV3ZmL3I3c1kzNkV6OTRGZEVMQndvUm5LMkkvekVJMjhaOTZGYzNTRDFObjN5NEVMbWYKQ016TkZ4cWtSNi80MmZ6ZGtLK0hkNmxPaW9PU3hqWEZoSnUvcTJ2cjNWUm9mUTZTcDQ5SHQwRldxU0x2d3JLNQppQVVQd2s0azRSR0EvUEpxdWt0SlZwa0doR0M0OHluc0VXT1FNVjJ5eGh2MGlENDExRVBvbXQvRkxERkcxZkpKClZkQWozYmNEdTJlMW8xUFd6VFFPYVVBR0k3TUlxcHhwbmVScDN6d21KQ0hzYkt1cTBjTVVlQVY5T1RHYnhvMlcKdTFyQ05UU2pmMENFVGFCajVZWW9Fck9SSVFXdHk1emxHNW1sNFZEZnI4Q1FHT2xNU3VVMytVWXBVZWJSOGNDdwpMZzhUa3U0emUwUVdRblBqK01rY25qSmtabzl2YlVXSTVHWkoxWnlWYWpsWTVEb25LbHV0VFNQNXJxUnM3Njc5CkdUSGdnL1Uwem0yVXQ1ejZjRE55aERYK2crR2ZrcVhXNnFlNkJwMy9xVFA5SUpxcnoxaHNiWDFHYm9yYldySXQKZU5ndXZmVHIvMUQyNHFPdWJsQ1lFNk1scmdteTE2OVkvQWRkUWV2ODV0TWlXRjJWWHFtcE5OUU16eVp2emNnbQp2QUpFOGh5cHJFbEZEbEpjK1BlUHlCbi95L0k1dXJiRjFMV0YrYkgzTlBXSGhIYUZzQkVLZFNwZUtlQnhBZ01CCkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRNzJXblRhVXg0Y25qQmlkRzF0NlNSc1BwcFdqQWZCZ05WSFNNRUdEQVcKZ0JRNzJXblRhVXg0Y25qQmlkRzF0NlNSc1BwcFdqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUNBUUNBM0RWR0FXcHRRUUVGYy9jUnhJd0s4bmFQNUdvSDJXRlpweXk1a3U5NjNyV1RpUFBTCklvMmptV3ovWWJFSzJDRWoxYUdDdlNGR093ZXlnZU0xaHAvNlUrM21RUk9qdmhLRzAzMFVNL2NHMjhLQXVtYmMKdktkaTBNcTRDeDFXL3hiU1BaWEtsUGhNdmhuNTFUQmZHdnNLOHBlUXRBcmxLWmlScUZYOHQxaCtwaWoxRTdBTQpITS9leWNyZ1BJRU1sMUhxNDVvZ2tOd0I5UTYwUktzV1NGd2FDOVVEaVNTTUNVVjl4c1lsUjlEMG94ZUQrSkpqCjVmMC84TllVVEQvTXVTbGhBRWpXSHBWVWNwQXFGVUtSdjhsMDEvQ3VYaWpOZnBUUG5hejgwTk03WWF3bDBMT0cKRExrSWhUU2ZTbHdKTmYrTVZRYTk3b3loV1VXeWIxRGNmRC9FcHpabW54N25xMUFpSUhZL0tIOWpNdkFMWkJBdwpZOW9tMXlYZ1hMUUNUMzZGdm1qVDVqZmNvc2JRZ0NHeEgwWDRtMk1XM3BOZHZwR2tYMDlzdjJENEtRQUJxNHBCCkZtT2RteE9KY1hqNTYyRkM4UFpaMGNOYU5iZk9rVkhzVjZyQXp0YjJ5RnJWOFZWNzhCb01lYVViTFg5S2JFMEUKQW1jQzRPekp3OTk1bHdaR2J0NVlKYk42Nnd4V1JNSEdYdmRuN0xmcHdnQjBtSzlPRUlFZytTTnRZdlVLaTRNWQpnT1Y4RUxtTmNpRWNrZEl2NUNUV3Q3dElRQmFxbkJYd3ZZNFY3WmxwU0hsOFBXaEpEZDQ0dmFOMmJ1WHAyV3RhCjhwVzB5NkhBejhMMUdpZXZRQUdEWjJWQ1FNWW82bm5yL1JGQkdDZ2ljVVkzWUp0VmFWQ2x6aW5HL1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
    server: https://k8sapi-prod.domain.lan:6443
  name: k8s
contexts:
- context:
    cluster: k8s
    user: david.curran@mycompany.com@k8s
  name: k8s
current-context: k8s
kind: Config
preferences: {}
users:
- name: david.curran@mycompany.com@k8s
  user:
    auth-provider:
      config:
        client-id: ldapauth
        client-secret: aoQ9JKU0KhNsz2V
        id-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2RleC5kb21haW4ubGFuIiwiaWF0IjoxNTgxMDc3ODQ1LCJleHAiOjE2MTI2MTM4NDUsImF1ZCI6ImxkYXBhdXRoIiwic3ViIjoiQ21WRFRqMUVZWFpwWkNCRGRYSnlZVzRzVDFVOVJHVjJaV3h2Y0cxbGJuUmZUazlVTEU5VlBVNXZkSFJwYm1kb1lXMWZTVlJQTEU5VlBWUmxZMmh1YjJ4dloza3NUMVU5UkdWd1lYSjBiV1Z1ZEhNc1JFTTlaSEl0Wm05emRHVnlMRVJEUFd4aGJoSUViR1JoY0EiLCJuYW1lIjoiRGF2aWQgQ3VycmFuIiwiZW1haWxfdmVyaWZpZWQiOiJ0cnVlIiwiZW1haWwiOiJkYXZpZC5jdXJyYW5AbXljb21wYW55LmNvbSIsImF0X2hhc2giOiJORHRaUGdrYjZBOE4wdkpzUXRhMUlnIn0.YdkofQiadvmgaIs2zj0neWJi2YlSTEqhVUeEbeB9d5M
        idp-issuer-url: https://dex.domain.lan
        refresh-token: Chl5emY3ZWxwb3d2c21zZWRmN3Z4bGllanI1Ehlhenc3bmpnaXdqYmo3Y240cGxjaWdsMmtu
      name: oidc
```

**kubectl output**
$> kubectl --kubeconfig kubeconf  get nodes -v=10
I0207 12:31:01.747636   11983 loader.go:375] Config loaded from file:  kubeconf
I0207 12:31:01.757759   11983 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.16.1 (linux/amd64) kubernetes/d647ddb" 'https://k8sapi-prod.domain.lan:6443/api?timeout=32s'
I0207 12:31:01.807003   11983 round_trippers.go:443] GET https://k8sapi-prod.domain.lan:6443/api?timeout=32s 401 Unauthorized in 49 milliseconds
I0207 12:31:01.807093   11983 round_trippers.go:449] Response Headers:
I0207 12:31:01.807135   11983 round_trippers.go:452]     Cache-Control: no-cache, private
I0207 12:31:01.807176   11983 round_trippers.go:452]     Content-Type: application/json
I0207 12:31:01.807216   11983 round_trippers.go:452]     Content-Length: 129
I0207 12:31:01.807254   11983 round_trippers.go:452]     Date: Fri, 07 Feb 2020 12:31:01 GMT
I0207 12:31:01.816561   11983 request.go:968] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
I0207 12:31:01.835060   11983 cached_discovery.go:121] skipped caching discovery info due to Unauthorized
...
I0207 12:31:02.132401   11983 helpers.go:199] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}]

**Keys in etcd**
```
ETCDCTL_API=3 etcdctl --endpoints https://10.4.5.194:2379 --cacert="etcd-ca.pem" --key="etcd-key.pem" --cert="etcd-crt.pem" get /registry/dex.coreos.com/ --keys-only --prefix
/registry/dex.coreos.com/offlinesessionses/auth/bj4c4y6ahgar4                                                                                                                                                                                                     /registry/dex.coreos.com/refreshtokens/auth/yzf7elpowvsmsedf7vxliejr5
/registry/dex.coreos.com/signingkeies/auth/openid-connect-keys
```

**Keys shown in dex web UI**
from *dex.domain.com/keys*
```
{
  "keys": [
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "5405ab900adf7bda958c83c90d2a2f124184188e",
      "alg": "RS256",
      "n": "rl9XUMh8wyDlfEi-BnhBX7n-fwIri2l4MPBigNeM9eXtURKVDW1KqkYBNCEA2gLuAKyySq9MfPVbQW9XgpLIPz5OYirFBP-N9bxgdkzO-J7aNF7EsiusLeePt3R4LNYg9YIPLkP2xjykgGYvOodobA_Ho8w444aO3vzznj6n2RZAwAv4ApANrXq75ez0KjLI-XegyWZxWvGUE4DSvQaz606X69viETSZUGixDJeitagHYOmME3L15Z0I1dPnwYV3iKRHceSeuyoHn2tN-SHzg7A4eIayPKUS4pKHuSK5gNflu8l7MsoQT310MfBF7mJvRHO9fRoLlUbWHlSlmVbmoQ",
      "e": "AQAB"
    },
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "84c82c43535ecdf7149f010aa262a9ab965db09a",
      "alg": "RS256",
      "n": "uNGrkdi9rJSSUbn699rETrUVwsZXtHRq6D8InpDvwoVUaGDc5VCdZc5DaHYFHYkXW_fKDtdHK1uCQaQSyaeye2tnXZvpuzsBkDEuJp3kuHi6MizBCNdwwgsaSnM0kY-oVpMq__fUouQkVMFPi1mvHkb5cmuwIO1wbZAOkupLJSt6XkC0P3ypnI6oGxub7k1xDoQF4fhQxgeTq813JuiGaSTl7YQex2jrHlkFmUdVlbkjCswefl9FNaY-2OZe7kkPABeLeV1KfDp5RS_mVFLZCMCuK5_RoVtxA7F_iFcEmUxAHOBzp7IY7GA_TjZTU4iIQl8hcTstVmkbUeKC0zHemw",
      "e": "AQAB"
    },
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "0849073f5d6fd17fbf6523e7e4d25e478f23fafe",
      "alg": "RS256",
      "n": "rT3XgrtY1420c3CL0VfLuyyz_DvKlNeH6-MElSj3DFqIKUsNmwgiExiDQwbNlQwcO-W163cZ55ki6m1zeTQgpft6ri_9v8kcZ7rD8CdxuCnV3O2WBtX3St56N70R8tq4-oDoFgO0Bg7WhXF2pEhkwrN_QfICkHY29aeyNOQ1vrU2AQ9vQHzTNSxiIvMrNWEVhO1jaaqfE9Y6wrqECRX0Y2MfybBR3Ntkii2SKXQt8wPdrfJj5_9W6UQTsU16r0CQGwSmqi23NOadS7Fq9nNAA6yF62ClkZotNWBgOOW_59pqgvu9bTCvoKncurhzqJRnh6GtNp5TK1PMHMGU7DhcXw",
      "e": "AQAB"
    },
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "763d4db5bdb3b7752a6b62537761d8ba7ef365a0",
      "alg": "RS256",
      "n": "r3PMuQ5EjSo4lJwqoWSQZ9wAFLUY59qZZ4p9lb_933bjp0y5WS11mdCPscjj_2IjJA3dTYcXik6cNfwUJMvXxxpTk3-4wO04JDSeDkJkcPZx0qrdFmvV9f5h_nYDdnZuo8e_5ZiezuuURBHb_dKNgrzynoiBCc3wZlba6CZZVXaIMTK7S1mehfr2fHP7dxFIS-VEF9khuwYfh2dIYAxhFjCi64QZfQoIhdIQ-8DZvL1fwjaRMDg3Ro4GHaASyPkB-xTTcOKm8sSPyT-uJ2Pgs6vMgz7I1x0Bogg84b1oyh75rN9LYbNlzXt2j9dtwcdFwUH2zUl4EbwNaZLbiexs4w",
      "e": "AQAB"
    },
    {
      "use": "sig",
      "kty": "RSA",
      "kid": "8e68cc9f625f68f32440582d92673fa6052be4c8",
      "alg": "RS256",
      "n": "x29TYxh_g1CgNdxbSc9HcfTDJpdkBi0RVH2awRIBU_Z4qLS9tekmVwvmpA7wEOb8NRwYz-VZgipCAMNRy7aXl2DuMS0v10dw0cGS7Cg7ebJVTWwlyDjXnqmSFvYlnideRZDTY5xUAXMhGj3m9vmE_X2lYsU54e659hK6AYSrrjeyGe8YqL3hynhz7QTGAbba2c6J1xjjaVJBWdz7JFnP6hAFiUE7OYVNXG5hD7kzxvEHG3n5OWG_mMxIPaP1bI3WZQKlHkeJCKvyf_KguPfJuqnuyO_bswckyyaiVTXo-3zqViWj0GHCfnfFXNK3txHWe5U0yt-_1xT1CTviQkv2hQ",
      "e": "AQAB"
    }
  ]
}
```

**Kuberentes API config** (OIDCS specific bits)
```
...
    - --oidc-issuer-url=https://dex.domain.lan
    - --oidc-ca-file=/etc/ssl/certs/openid-ca.pem
    - --oidc-client-id=ldapauth
    - --oidc-username-claim=email
    - --oidc-groups-claim=groups
...
```

I don't see errors in the logs for Dex
```
time="2020-02-07T12:10:08Z" level=info msg="login successful: connector \"ldap\", username=\"David Curran\", preferred_username=\"\", email=\"david.curran@mycompany.com\", groups=[]"
time="2020-02-07T12:10:08Z" level=info msg="username \"dcurran\" mapped to entry CN=David Curran,OU=Development_NOT,OU=Nottingham_ITO,OU=Technology,OU=Departments,DC=domainr,DC=lan"
time="2020-02-07T12:10:08Z" level=info msg="performing ldap search DC=dr-foster,DC=lan sub (&(objectClass=person)(SamAccountName=dcurran))"
```

Not sure why I'm getting unauthorised errors. Are more keys supposed to be generated in etcd? Or have I got some crossed wires between what Dex/Gangway/Kubernetes are all expecting to see as a username?
