### ISSUE TITLE
MS AD login groups empty - question

### ISSUE THREAD

**Issue by rezagh2** [dexidp/dex#1651]
User is able to login but groups in the logs is empty:

`level=info msg="login successful: connector \"ldap\", username=..., groups=[]"`

```
userSearch:
        baseDN: ...
        username: sAMAccountName
        emailAttr: mail
        nameAttr: name
        idAttr: distinguishedName
        filter: "(objectclass=user)"
      groupSearch:
        baseDN: ...
        filter: "(&(objectClass=group)(CN=Rancher*))"
        userMatchers:
        - userAttr: distinguishedName
          groupAttr: member
        nameAttr: cn

```
and in the rbac:
```
    p, role:org-admin, *, *, */*, allow
    g, Rancher Admins, role:org-admin

```
in ldap user looks like:

```
cn <user's Name>
distinguishedName <CN=.., OU=>.
mail ...
name ...
memberOf <CN=..., OU=>
sAMAccountName <what user logs in with>
```

group looks like:
```
cn <group name>
member <CN=..,. OU=...>.
name <group name>
```

not sure what i am doing wrong...
