### ISSUE TITLE
Login error: failed to connect: LDAP Result Code 200 "Network Error": EOF

### ISSUE THREAD

**Issue by chetnuy** [dexidp/dex#1675]
When I try to log in to my account I get this error:
Login error: failed to connect: LDAP Result Code 200 "Network Error": EOF

```
 connectors:
  - type: ldap
    id: ldap
    name: LDAP
    insecureNoSSL: true
    insecureSkipVerify: true

    config:
      host: ipa.freeipa.dtln.com:389
      userSearch:
        baseDN: cn=users,dc=ipa,dc=freeipa,dc=dtln,dc=com
        filter: "(objectClass=posixAccount)"
        username: uid
        idAttr: uid
        emailAttr: mail
      groupSearch:
        baseDN: cn=groups,dc=ipa,dc=freeipa,dc=dtln,dc=com
        filter: "(objectClass=group)"
        userMatchers:
        - userAttr: uid
          groupAttr: member
        nameAttr: name
```

**Comment by jenting** [comment]
@chetnuy, maybe the config should like this.

```
connectors:
- type: ldap
   id: ldap
   name: LDAP
   config:
     host: ipa.freeipa.dtln.com:389
     insecureNoSSL: true
     insecureSkipVerify: true
     userSearch:
        baseDN: cn=users,dc=ipa,dc=freeipa,dc=dtln,dc=com
        filter: "(objectClass=posixAccount)"
        ...
```
