### ISSUE TITLE
OpenShift rootCA config option doesn't seem to work

### ISSUE THREAD

**Issue by yann-soubeyrand** [dexidp/dex#1693]
Hello,

I expected the following config to work

```
connectors:
  - id: "openshift"
    type: "openshift"
    name: "OpenShift"
    config:
      issuer: "https://api-int.openshift.example.com"
      rootCA: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
      clientID: "clientID"
      clientSecret: "clientSecret"
      redirectURI: "https://argocd.apps.openshift.example.com/api/dex/callback"
      groups:
        - "openshift-admins"
```

but the following error is present in Dex logs (and login with OpenShift doesn't work)

```
failed to initialize server: server: Failed to open connector openshift: failed to open connector: failed to create connector openshift: failed to query OpenShift endpoint Get https://api-int.openshift.example.com/.well-known/oauth-authorization-server: x509: certificate signed by unknown authority
```

`/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` is the path of OpenShift CA inside each pod and this path is readable by Dex (`openssl x509 -in /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -text` returns the expected result). Using an image containing curl, the following command works

```
curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://api-int.openshift.example.com
```

Am I missing something or is there a bug with rootCA config option?
