### ISSUE TITLE
Intermittent authentication failure while fetching user details in Github connector

### ISSUE THREAD

**Issue by praveen0106** [dexidp/dex#1713]
Hello Dex Team, 
We are facing an intermittent 401 while logging in with Github in all our environments. This is random and intermittent in nature. Screen shot is provided below.

Pointer in the code where it might be failing:
https://github.com/dexidp/dex/blob/master/connector/github/github.go#L257

**Screenshot:**
<img width="1522" alt="Screenshot 2020-05-18 at 10 08 09" src="https://user-images.githubusercontent.com/12875775/82174886-c51f7400-98ef-11ea-87d4-f0e0cd9c0d13.png">

**YAML config:**

```
issuer: $APP_DOMAIN/dex
connectors:
    type: github
    id: github
    name: github
    config:
      clientID: XXXXXXXXXXXXXX
      clientSecret: XXXXXXXXXXXX
      redirectURI: $APP_DOMAIN/dex/callback
      loadAllGroups: true
```
