### ISSUE TITLE
Unable to login using LDAP, how to change change LDAP filter on dex configuration?

### ISSUE THREAD

**Issue by riupie** [dexidp/dex#1727]
I got this error:
```
time="2020-06-03T10:36:19Z" level=error msg="ldap: no results returned for filter: \"(&(objectClass=user)(name=ragung))\"" 
time="2020-06-03T10:37:26Z" level=info msg="performing ldap search OU=kubernetes,DC=ldap,DC=rahmatawe,DC=com sub (&(objectClass=user)(name=agung@rahmatawe.com))"
```

Actually I dont have `objectClass=user` so I change that to `objectClass=person` on dex configuration:

```
    connectors:
    - type: ldap
      id: ldap
      name: LDAP
      config:
        host: ldap.rahmatawe.com:389
        insecureNoSSL: true
        insecureSkipVerify: true
        bindDN: CN=admin,DC=ldap,DC=rahmatawe,DC=com
        bindPW: Elpsy12! #Add Administrator password
        userSearch:
          baseDN: OU=kubernetes,DC=ldap,DC=rahmatawe,DC=com
          filter: "(objectClass=person)"
          username: mail
          idAttr: uid
          emailAttr: mail
          nameAttr: mail
```

But when I see log, it still use filter (objectClass=user). Could I change that?
