### ISSUE TITLE
Github connector doesn't provider group claims

### ISSUE THREAD

**Issue by nmiculinic** [dexidp/dex#1770]
I'm trying to use github connector:

```yaml
    - type: github
      id: github
      name: GitHub
      config:
        clientID: <redacted>
        clientSecret: <redacted>
        redirectURI: <redacted>
        loadAllGroups: true
```

and I manage to successfully log in from my GitHub account, but there's no group claim in the IDToken. As I've read the docs, https://github.com/dexidp/dex/blob/master/Documentation/connectors/github.md , especially the:

```
    # If neither 'org' nor 'orgs' are specified in the config and 'loadAllGroups' setting set to true then user
    # authenticate with ALL user's Github groups. Typical use case for this setup:
    # provide read-only access to everyone and give full permissions if user has 'my-organization:admins-team' group claim. 
```

part I expected group claims in the resulting IDToken. But to no avail. What am I doing wrong?
