### ISSUE TITLE
dex github login error

### ISSUE THREAD

**Issue by arnoldas500** [dexidp/dex#1840]
trying to add github login for kubeflow using dex. I can see the github login option but the moment I click it I get a "Internal Server Error
Login error."

Does not bring me to a github login page nor show any other messages. Have tried on different browsers too with same error.

**Comment by ArchiFleKs** [comment]
I have the same issue with github and dex v2.15.0. I have try every possible callback URL to no avail

```
issuer: https://dex.k8s.particule.xyz
storage:
  config:
    inCluster: true
  type: kubernetes
logger:
  level: debug
web:
  http: 0.0.0.0:5556
connectors:
- clientID: *******
  clientSecret: *******
  id: github
  name: Github
  orgs:
  - name: particuleio
    teams:
    - owners
  redirectURI: https://dex.k8s.particule.xyz/callback
  type: github
oauth2: 
  alwaysShowLoginScreen: false
  skipApprovalScreen: true
staticClients:
- id: oidc-auth-client
  name: oidc-auth-client
  redirectURIs:
  - https://kubectl.k8s.particule.xyz/callback
  - https://dashboard.k8s.particule.xyz/oauth2/callback
  secret: ******
enablePasswordDB: true
```

I keep getting :
```
time="2020-11-01T16:22:42Z" level=error msg="Connector \"github\" returned error when creating callback: expected callback URL \"https://dex.k8s.particule.xyz/callback\" did not match the URL in the config \"\""
```
