### ISSUE TITLE
(question): Pomerium->Dex->Auth0 groups ?

### ISSUE THREAD

**Issue by lukasmrtvy** [dexidp/dex#1850]
I need little help with integrating Pomerium->Dex->Auth0 with groups support.

Dex config:
```
- type: oidc
  id: auth0
  name: Auth0
  config:
    issuer: https://<redacted>.eu.auth0.com/
    clientID: <redacted>
    clientSecret: <redacted>
    redirectURI: https://dex.<redacted>/callback
    scopes:
    - openid
    - profile
    - email
    claimMapping:
      groups: 'https://example.com/claims/groups'
      preferred_username: email
    getUserInfo: true
```

Auth0 rule snippet:
```
function (user, context, callback) {
  var namespace = 'https://example.com/claims/'; 
  context.idToken[namespace + "groups"] = user.groups;
  callback(null, user, context);
}
```

Pomerium config:
```
provider: oidc
url: https://dex.<redacted>
clientID: pomerium
clientSecret: <redacted>
scopes:
- openid
- profile
- email
- groups
policy:
  - from: https://whoami.<redacted>
    to: https://whoami.<redacted>
    allowed_idp_claims:
      groups:
      - admins
```

Latest `pomerium/pomerium:master` image implements allowed_idp_claims (https://github.com/pomerium/pomerium/pull/1542)

But seems that group, nor preferred_username values are not claimed. Any idea why ?
