### ISSUE TITLE
issues with invalid UTF format for dex UI

### ISSUE THREAD

**Issue by bernadinm** [dexidp/dex#1854]
Currently there is a bug when trying to get kubeconfig access. When pulling kubeconfig the client-secret displays `&#43` instead of `+` 

```
        client-secret: &#43;/CSAqswfyLOrGbnrDa21B==
```

This is what it looks like when generating the kubeconfig.

```
apiVersion: v1
kind: Config
clusters:
- name: test-environment
  cluster:
    server: https://api.test-environment.dev
    certificate-authority-data: <removed>
users:
- name: test-environment
  user:
    auth-provider:
      name: oidc
      config:
        client-id: kubectl
        client-secret: &#43;/CSAqswfyLOrGbnrDa21B==
        id-token: <removed>
        idp-certificate-authority-data: <removed>
        idp-issuer-url: https://ingress.test-environment.dev/identity
        refresh-token: <removed>
contexts:
- name: test-environment
  context:
    cluster: test-environment
    user: test-environment
current-context: test-environment

```
