### ISSUE TITLE
Allow using Hashicorp Vault to sign JWTs/JWKs

### ISSUE THREAD

**Issue by brancz** [dexidp/dex#1879]
**Is your feature request related to a problem? Please describe.**
It would be great if dex didn't have to store signing keys in a database in plaintext.

**Describe the solution you'd like to see**
Allowing to use Hashicorp Vault as a signing mechanism would improve this from a security perspective. As vault never gives out the signing key itself. Dex would issue a request to Vault to sign a payload and Vault would return the signed payload. Similarly for verifying the signature.

**Describe alternatives you've considered**
The current approach.

**Additional context**
Primarily opening this to see if I understand the possibility for this correctly. I don't currently have time to implement this, but I may in the future. If anyone is keen on implementing this now though, don't hesitate :slightly_smiling_face: .

**Comment by sagikazarmark** [comment]
I think it's a great idea. PRs welcome.

**Comment by whs** [comment]
Did some [POC](https://github.com/wongnai/dex/tree/whs/vault-signer) and turned out great. Not sure if I have time to polish it into mergeable quality, but most of the ground work is done.

What works:

- Swapping betweeen database signer (current implementation) and Vault signer
- RSA 2048, EC256 signing (jwt.io do accept our signed JWT now)
- /auth, /keys

What needs to be done:

- Make sure tests still pass
- Write tests
- Test with actual OIDC consumer
- Test with RSA > 2048, EC > 256
- Check for any other places that are using storage.GetKeys
- Can we make GetKeys not required in storage?
- I think the config part needs to be redone as I want Vault database credentials support too

**Comment by brancz** [comment]
> Can we make GetKeys not required in storage?

I think that's kind of the point, so I would actually expect this, but I'm not a dex maintainer, so take that with a grain of salt :) 

Without diving deeper, instinctively I would say, "signer" should be a new separate concept to storage and default to the current behavior, but be configurable to use vault.

> I think the config part needs to be redone as I want Vault database credentials support too

Do you mean using vault to issue database credentials? I agree this would be amazing, but I would leave that to be solved in a separate issue.

**Comment by whs** [comment]
>Do you mean using vault to issue database credentials? I agree this would be amazing, but I would leave that to be solved in a separate issue.

What I have in my branch is that I can configure Vault signer like this:

```yaml
signer:
  type: vault
  config:
    address: http://...
    mount: /transit
```

Which works great. However, if getting database credentials from Vault is planned then it might not be a good idea to put Vault config in signer. This would means either you have to use Vault signer to use Vault database credentials (what if you don't want to use either of them), or the user has to config Vault twice:

```yaml
database:
  type: sql-vault
  config:
    vault_address: http://...
    vault_mount: xxx
    vault_role: xxx

signer:
  type: vault
  config:
    address: http://...
    mount: /transit
```

What I believe should be:

```yaml
database:
  type: sql-vault
  config:
    vault_mount: xxx
    vault_role: xxx

signer:
  type: vault
  config:
    mount: /transit

vault:
  address: http://...
```

Although this might lead into more top level configuration. Say, people want to add support Google KMS would also need to add more top level key. I think the number of such secret manager that support *both* JWT signing and database secret is limited.

Even though we're not adding database credential support right now, I think this UX design should be considered beforehand.
