### ISSUE TITLE
Migrate Kubernetes storage CRDs API version to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by nabokihms** [dexidp/dex#1895]
#### Is your feature request related to a problem?
Starting from Kubernetes 1.22, API version `apiextensions.k8s.io/v1beta1` [will no longer be available](https://github.com/kubernetes/kubernetes/issues/82022).

#### Describe the solution you'd like to see
Version `apiextensions.k8s.io/v1` is only available in Kubernetes >=1.16. We need some kind of mechanism to detect the Kubernetes version and deploy crds based on it.

#### Describe alternatives you've considered
Migrate to `apiextensions.k8s.io/v1` with losing the support of Kubernetes clusters 1.16>= 

It's not a big deal, though. Users with outdated Kubernetes clusters can turn off automatic crds creation and deploy them manually.

#### Additional context
There is a [link to the doc](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions) that contains some nuances about migration.

**Comment by nabokihms** [comment]
I thought it would be easier. Previously created CRDs in v1beta1 continue working fine. However, the problem is creating new CRDs in v1.

Difference between manifests which keep which contain same logic:

**v1beta1**
```yaml
apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: devicerequests.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: DeviceRequest
    listKind: DeviceRequestList
    plural: devicerequests
    singular: devicerequest
  version: v1
```
**v1**
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devicerequests.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: DeviceRequest
    listKind: DeviceRequestList
    plural: devicerequests
    singular: devicerequest
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
```

Problems:
* It is impossible to drop the v1beta1 API version support because of tests, so I decided to add a Kubernetes version detect method. Maybe it would be better to fix storage tests first.
* Code [here](https://github.com/dexidp/dex/blob/master/storage/kubernetes/k8sapi/crd_extensions.go) looks like a copied structures from client-go. Copying more code seems not the best approach.
