### ISSUE TITLE
Authenticate via kubectl cli without browser

### ISSUE THREAD

**Issue by antoineozenne** [dexidp/dex#1922]
#### Is your feature request related to a problem?
We need to authenticate (LDAP) without access to a browser (linux VM in console). This is currently not possible because Dex prompt for credentials via a browser.

#### Describe the solution you'd like to see
It would be great if Dex proposed a client (https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) who prompt to enter credentials on the command line (like https://github.com/gyselroth/kube-ldap-client-go-exec-plugin). The kube config file could be : 
```yaml
[...]
users:
- name: myuser
  user:
    exec:
      command: dex-client-binary
      args:
      - "all necessary args"
      apiVersion: "client.authentication.k8s.io/v1alpha1"
```

The idea is to replace the browser to prompt for credentials by a cli.

#### Describe alternatives you've considered
kubelogin is not an alternative because it required a browser to get credentials.
