### ISSUE TITLE
Failing to authenticate with Microsoft connector after redirect

### ISSUE THREAD

**Issue by mbychkowski-deloitte** [dexidp/dex#2005]
#### Expected behavior (what you expected to happen)
Redirect to Microsoft tenant and authenticate and redirect back to application signed-in and authenticated

#### Actual behavior (what actually happened)
Redirect to Microsoft tenant and authenticate, but redirects back to Dex with the following error:

```txt
Internal Server Error

Failed to authenticate: microsoft: get groups: Authorization_RequestDenied: Insufficient privileges to complete the operation.
```

#### Steps to reproduce

1. Microsoft connector config:
```yaml
    issuer: https://mydex.example.com/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556  
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    connectors:
    - type: microsoft
      id: microsoft
      name: Microsoft
      config:
        # Connector config values starting with a "$" will read from the environment.
        clientID: $CLIENT_ID
        clientSecret: $CLIENT_SECRET
        tenant: tenant.onmicrosoft.com

        # Dex's issuer URL + "/callback"
        redirectURI: https://mydex.example.com/dex/callback
```
2. Microsoft Graph:
![image](https://user-images.githubusercontent.com/73294831/108281318-8607a300-714d-11eb-98b6-f274f0d17c72.png)

3. Redirect back to application takes you back to Dex login with this message:
![image](https://user-images.githubusercontent.com/73294831/108280350-0af1bd00-714c-11eb-9500-b59c64a7b102.png)

#### Environment

- Dex version: v2.17.0
- Installation type (official docker image): quay.io/dexidp/dex:v2.17.0
