### ISSUE TITLE
celar groups in github connector

### ISSUE THREAD

**Issue by morgoved** [dexidp/dex#2120]
- Dex version:v2.26.0
- Storage type:
- Installation type (official docker image, helm chart, etc.): argocd

i created ord oauth app in org, created team, added users in team. But

can't get groups "login successful: connector \"github\", username=\"morgoved\", preferred_username=\"morgoved\", email=\"yesyes@mail.ru\", groups=[]"

    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: 91c7a1561f9c832a85f9
            clientSecret: $dex.github.clientSecret
          org: orgname
          loadAllGroups: true

tried use 
          orgs:
          - name: orgname
            teams:
            - admin
and had the same result.
how i can fix it?

**Comment by nabokihms** [comment]
Hello! I assume that you missed the `groups` scope. Could you ensure that you send it? Sending this scope to the auth endpoint is mandatory to get non-empty groups array in an id token.

You can found documentation about scopes here 
https://dexidp.io/docs/custom-scopes-claims-clients/#scopes

**Comment by ihalloum** [comment]
@nabokihms 
Please, I have checked the documentation about scope, but I don't know how to send scope ??

**Comment by demonkoryu** [comment]
@ihalloum You can find the scope configuration docs here: https://dexidp.io/docs/connectors/oidc/#configuration

**Comment by sylv-sam** [comment]
I finally figured out what was causing this issue for me. It was a mismatch of cases between the org name in github "MyOrg" vs the org name I passed in my dex config "myorg". By changing the dex config value to be "MyOrg" it worked. This is the final config which works

```
connectors:
- type: github
  id: github
  name: Github
  config:
    clientID: id
    clientSecret: secret
    teamNameField: slug
    useLoginAsID: true
    orgs:
    - name: MyOrg
      teams:
      - engineering
      - admin
```
