### ISSUE TITLE
Openshift connector incompatible with OCP 4.8 due to well-known configuration URL change

### ISSUE THREAD

**Issue by rene-dekker** [dexidp/dex#2238]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.30.0

### Storage Type

Kubernetes

### Installation Type

Custom container image

### Expected Behavior

In previous openshift versions, the Openshift internal OAuth server was available at:
(openshift.go:63) wellKnownURL := strings.TrimSuffix(c.Issuer, "/") + "/.well-known/oauth-authorization-server"
The issuer in this case would look something like `https://api.mycluster.example.com:6443` 

In OCP 4.8 the issuer has changed slightly to `https://oauth-openshift.apps.$CLUSTER_DOMAIN:6443` and the URL `https://oauth-openshift.apps.$CLUSTER_DOMAIN:6443/.well-known/oauth-authorization-server` does not exist. I can find the configuration at ` https://openshift.default.svc/.well-known/oauth-authorization-server` (from within the cluster) as described here: https://docs.openshift.com/container-platform/4.8/authentication/configuring-internal-oauth.html

### Actual Behavior

The Dex container fails with message:
> failed to initialize server: server: Failed to open connector openshift: failed to open connector: failed to create connector openshift: failed to query OpenShift endpoint Get "https://oauth-openshift.apps.apps.<mycluster.com>:6443/.well-known/oauth-authorization-server": dial tcp 123.45.67.89:6443: i/o timeout

### Steps To Reproduce

Create an Openshift v4,8 cluster with Dex v2.30.0
Follow [this guide](https://dexidp.io/docs/connectors/openshift) to create an Openshift OAuth connector

### Additional Information

(openshift.go:63) wellKnownURL := strings.TrimSuffix(c.Issuer, "/") + "/.well-known/oauth-authorization-server" makes the well-known configuration a static URL. This used to be fine, but with OCP 4.8 the URL changed.

A possible fix to this bug would be to make the well-known configuration a configurable variable in the `openshift.Config` or to detect what Openshift version is running.

### Configuration

```
 config.yaml: |
    connectors:
    - config:
        clientID: $CLIENT_ID
        clientSecret: $CLIENT_SECRET
        issuer: https://oauth-openshift.apps:OCPHOST
        redirectURI: https://APPHOST:PORT/dex/callback
        rootCA: /etc/ssl/certs/idp.pem
      id: openshift
      name: openshift
      type: openshift
    issuer: https:/APPHOST:PORT/dex
```

_No response_
