### ISSUE TITLE
Switching from Login with Email to other login methods

### ISSUE THREAD

**Issue by tidunguyen** [dexidp/dex#2271]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.28.1

### Storage Type

Kubernetes

### Installation Type

Custom container image, Other (specify below)

### Expected Behavior

Start OAuth2 Flow with a connector.

### Actual Behavior

Internal Server Error
Database error.

### Steps To Reproduce

1. Set Up Dex with Email login and another connector
2. Go to Dex login page
3. Select `Login with Email`
4. Click `Select another login method.`
5. Choose `Login with GitHub` or `Login with Google`

### Additional Information

Container Image:
`quay.io/dexidp/dex:v2.28.1`

I already tried changing storage to:
```yaml
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
```

### Configuration

```yaml
issuer: http://10.0.1.1.nip.io/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
enablePasswordDB: true
# oauth2:
#   skipApprovalScreen: true
connectors:
  - type: github
    id: github
    name: GitHub
    config:
      clientID: *****
      clientSecret: *****
      redirectURI: http://10.0.1.1.nip.io/dex/callback
      useLoginAsID: false
  - type: google
    id: google
    name: Google
    config:
      clientID: *****
      clientSecret: *****
      redirectURI: http://10.0.1.1.nip.io/dex/callback
staticPasswords:
- email: user@example.com
  hash: *****
  username: user
staticClients:
- id: kubeflow-oidc-authservice
  redirectURIs: ['/login/oidc']
  name: 'Dex Login Application'
  secret: *****
```

### Logs

```shell
time="2021-09-13T08:37:12Z" level=info msg="config storage: kubernetes"
time="2021-09-13T08:37:12Z" level=info msg="config static client: Dex Login Application"
time="2021-09-13T08:37:12Z" level=info msg="config connector: github"
time="2021-09-13T08:37:12Z" level=info msg="config connector: google"
time="2021-09-13T08:37:12Z" level=info msg="config connector: local passwords enabled"
time="2021-09-13T08:37:13Z" level=info msg="listening (http) on 0.0.0.0:5556"
time="2021-09-13T08:37:39Z" level=error msg="Failed to set connector ID on auth request: connector is already set for this auth request"
```
