### ISSUE TITLE
Connectors that have IDs with URL-unsafe characters cannot be used successfully

### ISSUE THREAD

**Issue by bobcallaway** [dexidp/dex#2289]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.30.0

### Storage Type

In-memory

### Installation Type

Official container image

### Expected Behavior

Successful authentication through connector

### Actual Behavior

I get a 404 after selecting the connector in the browser, as the redirect url was: `http://dex-idp:8888/auth/auth/https:/any.valid.url?access_type=online&client_id=fulcio&code_challenge=eCv7jqfgdr6P0e9e565Gyi30Zcm8RSCl6nBgy6O3iOI&code_challenge_method=S256&nonce=1yuz7B7bfgn8kcyiRRR9en7XWyB&redirect_uri=http%3A%2F%2Flocalhost%3A5556%2Fauth%2Fcallback&response_type=code&scope=openid+email&state=1yuz75uFHa4CwGunc7tNhkNldZn`

### Steps To Reproduce

Having a connector defined with an ID that has URL-unsafe characters like this:

```
connectors:
- type: mockCallback
  id: https://any.valid.url/
  name: AlwaysApprovesOIDCProvider
```

### Configuration

```yaml
...
connectors:
- type: mockCallback
  id: https://any.valid.url/
  name: AlwaysApprovesOIDCProvider
...
```
