### ISSUE TITLE
Dex with etcd storage crashes after upgrading to version 2.29.0

### ISSUE THREAD

**Issue by marcozov** [dexidp/dex#2296]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.29.0

### Storage Type

etcd

### Installation Type

Official container image, Custom Helm chart

### Expected Behavior

Dex can keep using the etcd storage.

### Actual Behavior

Until dex 2.28.0 everything worked as expected.
Now (with version 2.29.0) we keep getting errors (see the logs section) and the dex application is always restarted.

### Steps To Reproduce

Upgrade dex to version 2.29.0 .

### Additional Information

The configuration (reported in the dedicated section) was unchanged.
etcd is deployed in the same Kubernetes cluster and namespace.
I also noticed the following logs on the istio sidecar (which is deployed on dex and etcd pods):
```
{"duration":0,"connection_termination_details":null,"requested_server_name":null,"bytes_sent":0,"route_name":null,"authority":null,"upstream_transport_failure_reason":null,"downstream_local_address":"10.32.2.101:2379","upstream_local_address":null,"x_forwarded_for":null,"authn_request_auth_principal":null,"upstream_service_time":null,"request_id":null,"response_code_details":"http2.invalid.header.field","authn_email":null,"authn_upn":null,"upstream_cluster":null,"downstream_remote_address":"10.32.32.59:56884","protocol":"HTTP/2","path":null,"start_time":"2021-10-13T13:09:54.316Z","authn_name":null,"upstream_host":null,"osdp_env":"dev","user_agent":null,"authn_source_principal":null,"response_code":0,"response_flags":"DPE","method":null,"bytes_received":0}
```
Could it be that some header is missing, for some reason?
I also tried to remove the istio sidecars, but the dex keeps failing.

### Configuration

```yaml
issuer: https://my.auth.com/dex/
storage:
  type: etcd
  config:
    endpoints:
      - auth-etcd-headless.auth.svc.cluster.local:2379
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
# expiry:
#   deviceRequests: "5m"
#   signingKeys: "30m"
#   idTokens: "1h"
oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
enablePasswordDB: false
staticClients:
  - id: example-app
    # this example app can and should be removed, once we have a jwt issuing webservice
    redirectURIs: ['http://127.0.0.1:5555/callback']
    name: 'Dex Login Application'
    # this is the secret hardcoded into the sample app. I therefore would like to keep it here until we have a jwt issuing service
    secret: super-secret
  - id: oauth2-proxy
    redirectURIs: # this is a list of internal services redirect URIs.
      - "https://service1.com/oauth2/callback"
      - "https://service2.com/oauth2/callback"
      - ...
    name: 'Oauth2 proxy'
    secretEnv: OAUTH2_PROXY_SECRET
connectors:
  - type: microsoft
    id: aad-osdp-oidc
    name: Microsoft
    config:
      clientID: aaaaaaaa-aaaa-aaaa-aaaa-eeeeeeeeeeee. # client ID for app configured on microsoft
      clientSecret: $MICROSOFT_CLIENT_SECRET
      redirectURI: https://auth.dev.osdp.open.ch/dex/callback
      tenant: qqqqqqqq-xxxx-wwww-vvvv-zzzzzzzzzzzz. # azure tenant ID
      groupNameFormat: id
      useGroupsAsWhitelist: true
      groups: # azure group IDs
        - "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
        - "ffffffff-gggg-hhhh-iiii-jjjjjjjjjjjj"
        - ....
```

### Logs

```shell
time="2021-10-15T07:53:51Z" level=info msg="config using log level: debug"
time="2021-10-15T07:53:51Z" level=info msg="config issuer: https://my.auth.com/dex/"
time="2021-10-15T07:53:51Z" level=info msg="config storage: etcd"
time="2021-10-15T07:53:51Z" level=info msg="config static client: Dex Login Application"
time="2021-10-15T07:53:51Z" level=info msg="config static client: Oauth2 proxy"
time="2021-10-15T07:53:51Z" level=info msg="config connector: aad-osdp-oidc"
time="2021-10-15T07:53:51Z" level=info msg="config skipping approval screen"
time="2021-10-15T07:53:51Z" level=info msg="config refresh tokens rotation enabled: true"
{"level":"warn","ts":"2021-10-15T07:53:52.339Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000518700/#initially=[auth-etcd-headless.auth.svc.cluster.local:2379]","attempt":0,"error":"rpc error: code = Unavailable desc = error reading from server: read tcp 10.32.27.15:50790->10.32.17.25:2379: read: connection reset by peer"}
{"level":"warn","ts":"2021-10-15T07:53:53.367Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000518700/#initially=[auth-etcd-headless.auth.svc.cluster.local:2379]","attempt":1,"error":"rpc error: code = Unavailable desc = error reading from server: EOF"}
{"level":"warn","ts":"2021-10-15T07:53:54.393Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000518700/#initially=[auth-etcd-headless.auth.svc.cluster.local:2379]","attempt":2,"error":"rpc error: code = Unavailable desc = error reading from server: EOF"}
{"level":"warn","ts":"2021-10-15T07:53:55.418Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000518700/#initially=[auth-etcd-headless.auth.svc.cluster.local:2379]","attempt":3,"error":"rpc error: code = Unavailable desc = error reading from server: EOF"}
{"level":"warn","ts":"2021-10-15T07:53:56.334Z","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc000518700/#initially=[auth-etcd-headless.auth.svc.cluster.local:2379]","attempt":4,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
failed to initialize server: server: failed to list connector objects from storage: context deadline exceeded
```
