### ISSUE TITLE
Authcode login dex returns wrong state value

### ISSUE THREAD

**Issue by phxgbl** [dexidp/dex#2347]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.30.2

### Storage Type

In-memory

### Installation Type

Binary

### Expected Behavior

Local connector to redirect with **same state value** sent by the client

### Actual Behavior

state value sent by client and the one returned by Dex doesn't match

### Steps To Reproduce

1)Download and start latest dex release 2.30.2.
2)Run the go-oidc example [https://github.com/coreos/go-oidc/tree/v3/example/idtoken ](url) 
3)Login using a static password
4)Login will be successful and redirected to the client app with the **wrong state** .

### Configuration

```yaml
issuer: http://127.0.0.1:5556/dex

storage:
  type: sqlite3
  config:
    file: dex.db

web:
  http: 127.0.0.1:5556

telemetry:
  http: 127.0.0.1:5558

grpc:
  addr: 127.0.0.1:5557

staticClients:
  - id: example-app
    redirectURIs:
     - 'http://127.0.0.1:3000/auth/oidc/callback'
     - 'http://127.0.0.1:5555/callback'
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

connectors:
  - type: mockCallback
    id: mock
    name: Example

enablePasswordDB: true

staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
```
