### ISSUE TITLE
Microsoft connector requesting too much access

### ISSUE THREAD

**Issue by dotMikeH** [dexidp/dex#2442]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

The Microsoft connector should be using least privilege access when it comes to Microsoft Graph, it's an incredibly powerful and dangerous API. As it sits, it's requesting the delegated permission, `Directory.Read.All` (https://github.com/dexidp/dex/blob/master/connector/microsoft/microsoft.go#L39), which gives this access to way too much data (Users, Groups, Devices, Applications, etc.). For something that is only suppose to be reading security groups this will only need `GroupMember.Read.All`.

### Proposed Solution

From looking at the connector's code you are hardcoding the specific permission and I can tell you are using the v2.0 endpoints. This means you can just simply use `https://graph.microsoft.com/.default` as a scope,  which expands to what is assigned to the Azure App Registration at the time of sign-in for a user or at the very least use the `GroupMember.Read.All` delegated permission
If the reason this requires `Directory.Read.All` is because it's using the `/v1.0/directoryObjects/getByIds` query to take the Group IDs from  `/v1.0/me/getMemberGroups` to resolve them to their group name, it would better to do this query
```
GET https://graph.microsoft.com/v1.0/me/memberOf?$count=true&$top=999&$filter=securityEnabled eq true&$select=id,displayName

Headers:
Authorization: bearer <token>
Content-Type: application/json
ConsistencyLevel: eventual
```
**Note:** $count=true and the ConsistencyLevel header is required for this query

which returns as
```
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#directoryObjects(id,displayName)",
    "@odata.count": 1,
    "value": [
        {
            "@odata.type": "#microsoft.graph.group",
            "id": "GUID",
            "displayName": "MY-GROUP-NAME"
        }
    ]
}
```

I've also verified that `GroupMember.Read.All` works for `/v1.0/directoryObjects/getByIds` even though the docs only states that `Directory.Read.All` is required.
**Response**
![group-query](https://user-images.githubusercontent.com/7277709/158681695-5e5dc787-ab41-4a47-8679-f3f0064fc95a.png)
**Token**
![toke-payload](https://user-images.githubusercontent.com/7277709/158681689-2d9358e0-8edd-4826-916e-4b0d84c8424d.png)

**Comment by fouadsemaan** [comment]
I am running into the same wall. Besides `Directory.Read.All`, is `GroupMember.Read.All` the only other permission you have added?

**Comment by dotMikeH** [comment]
@fouadsemaan Not on the team anymore that supports Azure AD at my company, but if I recall, yes it would have been the only permission assigned on another app registration for testing purposes using Postman for query validation.

**Comment by netiperher** [comment]
This is an old issue but I had great success Dex + Microsoft Entra (formerly known as Azure Active Directory) by switching to the plain `oidc` connector instead of the `microsoft` one. Then it is possible to use the normal oidc permissions (in MS Entra) without any `Director.Read.All` in order to get groups and/or roles:

```
    connectors:
      - id: microsoft
        name: Microsoft
        type: oidc
        config:
          issuer: https://login.microsoftonline.com/<tenant id>/v2.0
          clientID: "<application id>"
          clientSecret: "<client secret>"
          redirectURI: https://dex.example.com/callback
          # Required
          insecureSkipEmailVerified: true

          # Required when client is requesting group scope
          insecureEnableGroups: true
          # Optional when using MS roles instead of groups
          claimMapping:
            groups: "roles"

          # Optional when client is requesting offline_access scope
          promptType: "none"
          # Required when client is requesting offline_access scope
          scopes:
            - openid
            - profile
            - email
            - offline_access
```
