### ISSUE TITLE
Update kubernetes example to go throught the entrypoint

### ISSUE THREAD

**Issue by benjamin-bergia** [dexidp/dex#2449]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.30.0

### Storage Type

Kubernetes

### Installation Type

Official container image

### Expected Behavior

After reading https://github.com/dexidp/dex/issues/1099#issuecomment-1074105206, I tried to add templating to my configuration file and constantly had the following error:
`error parse config file /etc/dex/config.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Env.GITHUB_CONNECTOR_CLIENT_ID":interface {}(nil)}`

My config file, kubernetes deployment, environment variables, etc were all correct and based on the kubernetes example from this repository. After going again through the documentation, docker entrypoint, Dockerfile and sample config file, I realized that the [kubernetes example](https://github.com/dexidp/dex/blob/20e2e429b34086bc4ffbfbbae888f644ca1f1377/examples/k8s/dex.yaml#L28) is over writing the entrypoint.

### Actual Behavior

To avoid this, the container specs should be:
```yaml
      containers:
      - image: ghcr.io/dexidp/dex:v2.30.0
        name: dex
        args: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
```
This will preserve the entrypoint defined in the Dockerfile.

**Comment by tiwarisanjay** [comment]
I am keep on getting following error when trying to use the secret from Env. Secret works if I hard code the same. 
```
invalid client_secret on token request for client 
```
Tried all ways : 
```
clientSecret: $CLIENT_SECRET
or 
clientSecret: {{ Env.CLIENT_SECRET }} 
or 
${CLIENT_SECRET}

**Comment by nabokihms** [comment]
Related issue https://github.com/dexidp/dex/issues/2237 (it seems that it conflicts with the current one)

**Comment by nabokihms** [comment]
@tiwarisanjay, it is better to open a new issue or a discussion because we need more data to debug the problem. I assume the minimal will be the Dex version and how you deploy it.

**Comment by tiwarisanjay** [comment]
@nabokihms  https://github.com/dexidp/dex/issues/2553

**Comment by phoerious** [comment]
Same. I'm trying to use a secret for a staticClient from an environment variable in Dex 2.32.0 (deployed in Kubernetes). My Dex config.yaml is mounted from a ConfigMap and looks like this in the container:

```yaml
issuer: https://XXX
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
expiry:
  idTokens: 1h
connectors:
  - type: gitlab
    id: gitlab
    name: GitLab
    config:
      baseURL: XXX
      clientID: $GITLAB_APPLICATION_ID   # I can use this syntax here, but not down there
      clientSecret: $GITLAB_CLIENT_SECRET
      redirectURI: XXX
oauth2:
  skipApprovalScreen: true
staticClients:
  - id: abc
    secret: '{{ .Env.ABC_SECRET }}'   # Doesn't work
    name: 'ABC'
    redirectURIs:
      - XXX
```
