### ISSUE TITLE
Dex, Google connector, language selection and 400 error

### ISSUE THREAD

**Issue by reynico** [dexidp/dex#2493]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.31.1

### Storage Type

Kubernetes

### Installation Type

Official container image

### Expected Behavior

Login should go through no matter which language is selected.

### Actual Behavior

When using a Google connector, the login procedure fails just after I pick an account from the Google account chooser on the browser with the following error:
```
Something went wrong
Sorry, something went wrong there. Try again.
```

But if I change the language on the Google account chooser (even if I'm already in the English United States and I select the English United States again), it works.

URL when I do not manually choose the language:
```
https://accounts.google.com/o/oauth2/v2/auth/oauthchooseaccount?client_id=REDACTED.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fdex.domain.com%2Fcallback&response_type=code&scope=openid%20profile%20email&state=pxnws2f22sm5kdttdfpmpyckh&flowName=GeneralOAuthFlow
```

URL when I do choose the language:
```
https://accounts.google.com/o/oauth2/v2/auth/oauthchooseaccount?client_id=REDACYED.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fdex.domain.com%2Fcallback&response_type=code&scope=openid%20profile%20email&state=zglyedexaye3vjylkbv2mqd7h&hl=en&flowName=GeneralOAuthFlow
```

The solely difference seems to be `&hl=en` and that's what makes it to work.

### Configuration

```yaml
connectors:
  - type: oidc
    id: google
    name: google
    config:
      issuer: https://accounts.google.com
      clientID: $GOOGLE_CLIENT_ID
      clientSecret: $GOOGLE_CLIENT_SECRET
      redirectURI: https://dex.domain.com/callback
      userNameKey: email
```
```


### Logs

_No response_
