### ISSUE TITLE
Org definition using incorrect case can silently fail to pull github groups.

### ISSUE THREAD

**Issue by fivovic** [dexidp/dex#2499]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

v2.30.0-dirty

### Storage Type

Kubernetes

### Installation Type

Custom Helm chart

### Expected Behavior

A warning would be logged if the defined org within the github connector does not match the case used in the login name (as returned by the github api).

### Actual Behavior

Defining `A1Example` in the config when the org name is `a1example` will allow successful authentication but with an empty group list, and subsequently fail to apply any group specific access policies.

### Additional Information

This was discovered using dex bundled within the following helm chart:
https://artifacthub.io/packages/helm/argo/argo-cd/3.29.5#dex

### Configuration

```yaml
argo-cd:
  server:
    configEnabled: true
    config:
      url: https://argo.a1example.com
      dex.config: |-
        connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $GITHUB_CLIENT_ID
            clientSecret: $GITHUB_CLIENT_SECRET
            orgs:
            - name: A1Example
```

### Logs

```shell
Correct case:
`time="2022-04-26T15:02:55Z" level=info msg="login successful: connector \"github\", username=\"Fil Ivovic\", preferred_username=\"fivovic\", email=\"f.ivovic@a1example.co.uk\", groups=[\"a1example:admins\"]"`

Incorrect case:
`time="2022-04-26T15:02:55Z" level=info msg="login successful: connector \"github\", username=\"Fil Ivovic\", preferred_username=\"fivovic\", email=\"f.ivovic@a1example.co.uk\", groups=[]"`
```

**Comment by mmclane** [comment]
I am running into this issue too.

Its worth noting that the team names ARE case-sensitive.

**Comment by nabokihms** [comment]
Dex exports:
* A `slug`ified name of each team, so they are always lowercase names.
* Org name from the `login` field, a case-sensitive field.

However, even if the field is case-sensitive, it is still case-insensitive on the backend side.
<img src="https://user-images.githubusercontent.com/32434187/168315594-186b4de5-2e7f-42db-9a0f-3cc75c04050d.png" height=150/><img src="https://user-images.githubusercontent.com/32434187/168315741-176bc0c9-1533-4f49-8a9b-27578f235dbc.png" height=150/>

I think to close this issue, two actions are required:
1. Make case-insensitive org check for the GitHub connector
2. Add the information about how many groups were filtered

How to implement the first one is straightforward. For the second one, before working on it, I would like to wait for the https://github.com/dexidp/dex/issues/2020 first.

**Comment by lazedo** [comment]
`org: 123free`  also fails to get the groups and needs to be set as `org: '123free'` which might be not obvious to everybody, maybe adding a `note`  about that.

**Comment by mknapcok** [comment]
I encountered this issue too:
 
With dex.config:
``` 
connectors:
       - type: github
         id: github
         name: GitHub
         config:
           clientID: xxxxx
           clientSecret: $argocd-custom-secret:dex.github.clientSecret
         orgs:
         - name: org-name <tried also Org-name>
         loadAllGroups: true
```
         
 I'm successfully logging in but with field `groups` not populated.
`msg="login successful: connector \"github\", username=\"Michal Knapcok\", preferred_username=\"mknapcok\", email=\"xxx\", groups=[]`
