### ISSUE TITLE
invalid client_secret on token request for client  : Kubernetes  deployment 

### ISSUE THREAD

**Issue by tiwarisanjay** [dexidp/dex#2553]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

v2.30.0

### Storage Type

Kubernetes

### Installation Type

Official container image

### Expected Behavior

Dex deployment should pickup the CLIENT_ID and CLIENT_SECRET from environment which it does not pickup. 
I checked the code and there is no support for the same. 

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: dex
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.yaml: |
    issuer: {{ .Values.dex.config.issuer }}
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      # http: 0.0.0.0:5556
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/ssl/tls.crt
      tlsKey: /etc/dex/ssl/tls.key
    # Configuration for telemetry
    telemetry:
      https: 0.0.0.0:5558   
    connectors:
    - type: microsoft
      id: microsoft
      name: Microsoft
      config:
        clientID: {{ .Values.dex.config.clientid }}
        clientSecret: $CLIENT_SECRET
        redirectURI: {{ template "connector.redirectUrl" . }}
        tenant: {{ .Values.dex.config.tenantid }}
    staticClients:
    - id: {{ .Values.dex.config.clientid }}
      redirectURIs:
      - {{ .Values.dex.config.staticClient.redirectUrl }}
      name: 'Argo workflow'
      SecretEnv: CLIENT_SECRET
    enablePasswordDB: true
```

Deployment : 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: argo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex # This is created below
      containers:
      - image: ghcr.io/dexidp/dex:v2.30.0
        name: dex
        command: ["/usr/local/bin/dex", "serve", "/etc/dex/cfg/config.yaml"]
        ports:
        - name: https
          containerPort: 5556
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: dex-ssl
          mountPath: /etc/dex/ssl
          readOnly: true
        env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-client
              key: client-secret
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 5558
        #     scheme: HTTPS
      volumes:
      - name: dex-ssl
        secret:
          secretName: tls-secret
      - name: config
        configMap:
          name: dex
          items:
          - key: config.yaml
            path: config.yaml
```
As per document above code should pickup value of $CLIENT_SECRET from environment which is present  and I have validated the same. 
I see that os.GetEnv is used for staticClients with SecretEnv. But did not see that CLIENT_SECRET is picked up from environment. Seems like a missing piece. Tough k8s example yaml for dex is using this kind of variable. 
@nabokihms

### Actual Behavior

I get following error when authenticating with client : 
```
invalid client_secret on token request for client 
```
It works fine if I hard code the Client secret in configmap. 

### Steps To Reproduce

Just run your example k8 configuration with github connector mentioned in config.yaml configmap.  it should reproduce the issue as variable does not work in connectors. 

### Logs

```shell
invalid client_secret on token request for client
```

**Comment by jessesuen** [comment]
I think your problem is that `SecretEnv` should actually be `secretEnv` (lowercased s).

```yaml
    staticClients:
    - id: {{ .Values.dex.config.clientid }}
      redirectURIs:
      - {{ .Values.dex.config.staticClient.redirectUrl }}
      name: 'Argo workflow'
      SecretEnv: CLIENT_SECRET
```
