### ISSUE TITLE
OIDC Connector: Allow configuration of insecure issuer url 

### ISSUE THREAD

**Issue by jotdl** [dexidp/dex#2581]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Some upstream OIDC providers report a issuer_url which does not match the url of the discovery endpoint.  The [coreos/go-oidc](https://pkg.go.dev/github.com/coreos/go-oidc/v3@v3.2.0/oidc#InsecureIssuerURLContext) library used by dex provides a configuration option to handle such cases. As far as I am aware of this option can not be configured in dex yet.

### Proposed Solution

Make this configuration option available for OIDC Connectors as `insecureIssuerURL`.

This could look like the following:
```yaml
connectors:
- type: oidc
  id: legacy-oidc
  name: legacy-oidc
  config:
    ...
    insecureIssuerURL: "https://accepted-issuer-url.com"
    ...
```

### Alternatives Considered

I can't imagine any alternatives, except changing the upstream OIDC provider, but I would be happy to hear about any alternatives? Sadly changing the upstream OIDC provider is out of our reach.
