### ISSUE TITLE
Crowd connector does not return display name

### ISSUE THREAD

**Issue by ihulsbus** [dexidp/dex#2644]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.33.0

### Storage Type

SQLite

### Installation Type

Official container image

### Expected Behavior

Expected to get the user's display name after logging in via the Crowd connector in the `name` claim. 

### Actual Behavior

Crowd connector returns the username instead of the display name in the `name` claim, e.g.: johndoe instead of John Doe 

### Steps To Reproduce

1. Use official container
2. Use latest Crowd release (5.0.2 at the time of writing)
3. Create crowd connection and static client
4. Login
5. check the `/userinfo` endpoint. 
6. user claim shows username in the `name` claim instead of the display name

### Additional Information

Got:
```
{
    "iss": "https://localhost:5556",
    "sub": "<hash>",
    "aud": "testclient",
    "exp": 1661942538,
    "iat": 1661856138,
    "at_hash": "<hash>",
    "email": "johndoe@example.com",
    "email_verified": true,
    "groups": [
        "group"
    ],
    "name": "johndoe",
    "preferred_username": "johndoe"
}
```
Expected:
```
{
    "iss": "https://localhost:5556",
    "sub": "<hash>",
    "aud": "testclient",
    "exp": 1661942538,
    "iat": 1661856138,
    "at_hash": "<hash>",
    "email": "johndoe@example.com",
    "email_verified": true,
    "groups": [
        "group"
    ],
    "name": "John Doe",
    "preferred_username": "johndoe"
}
```

### Configuration

```yaml
issuer: https://localhost:5556
storage:
  type: sqlite3
  config:
    file: dex.db
web:
  http: 0.0.0.0:5556
telemetry:
  http: 0.0.0.0:5558
expiry:
  signingKeys: "6h"
  idTokens: "24h"
oauth2:
    skipApprovalScreen: true
    alwaysShowLoginScreen: false
staticClients:
- id: testclient
  redirectURIs:
  - 'urn:ietf:wg:oauth:2.0:oob'
  - 'http://localhost:8000/oidc/callback'
  name: 'TestClient'
  public: True
  secret: '<redacted>'
connectors:
- type: atlassian-crowd
  id: crowd
  name: Crowd
  config:
    baseURL: https://<baseurl>/crowd
    clientID: <client>
    clientSecret: <secret>
    usernamePrompt: username
    preferredUsernameField: name
```

### Logs

```shell
Not relevant
```
