### ISSUE TITLE
Page 404 occurs

### ISSUE THREAD

**Issue by sekarandevarajan** [dexidp/dex#2669]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

v2.33.1-dirty

### Storage Type

SQLite

### Installation Type

Binary, Official container image

### Expected Behavior

I am trying to add a openid connector for my "Vikunja todo app" for getting the LDAP service

### Actual Behavior

I am getting "404 page not found"

### Steps To Reproduce

In linux environnent and with server apache, the home page of DEX is still not display after many attempts and modifications on config files.  

### Additional Information

My Vikunja Openid Config :

```
auth:
  # Local authentication will let users log in and register (if enabled) through the db.
  # This is the default auth mechanism and does not require any additional configuration.
  local:
    # Enable or disable local authentication
    enabled: false

  # OpenID configuration will allow users to authenticate through a third-party OpenID Connect compatible provider.<br/>
  # The provider needs to support the `openid`, `profile` and `email` scopes.<br/>
  # **Note:** Some openid providers (like gitlab) only make the email of the user available through openid claims if they have set it to be publicly visible.
  # If the email is not public in those cases, authenticating will fail.
  # **Note 2:** The frontend expects to be redirected after authentication by the third party
  # to <frontend-url>/auth/openid/<auth key>. Please make sure to configure the redirect url with your third party
  # auth service accordingy if you're using the default vikunja frontend.
  # Take a look at the [default config file](https://kolaente.dev/vikunja/api/src/branch/main/config.yml.sample) for more information about how to configure openid authentication.
  openid:
    # Enable or disable OpenID Connect authentication
    enabled: true

    # The url to redirect clients to. Defaults to the configured frontend url. If you're using Vikunja with the official
    # frontend, you don't need to change this value.
    redirecturl: https://my.vikunja.com/auth/openid/

    # A list of enabled providers
    providers:
      # The name of the provider as it will appear in the frontend.
      - name: dex

        # The auth url to send users to if they want to authenticate using OpenID Connect.
        authurl: "https://my.ldap.com"

        # The client ID used to authenticate Vikunja at the OpenID Connect provider.
        clientid: vikunja

        # The client secret used to authenticate Vikunja at the OpenID Connect provider.
        clientsecret: mySecretIDisGood 
```

### Configuration

```yaml
issuer: http://my-domain.com/

storage:
  type: sqlite3
  config:
    file: /opt/dex/dex.db

web:
  http: 127.0.0.1:5556

connectors:
- type: ldap
  id: my-ldap
  name: MY LDAP
  config:
    host: ldap.server.com:389
    startTLS: true

    #userHeader: X-Forwarded-User
    #groupHeader: X-Forwarded-Group
    #staticGroups:
    #- default

    bindDN: uid=myusers,ou=peoples,dc=my,dc=ldapppp,dc=com
    bindPW: itIsmyPAsswORD

    usernamePrompt: Email Address

    userSearch:
      baseDN: ou=peoples,dc=ldapppp,dc=upmc,dc=com
      filter: "(objectclass=inetOrgPerson)"
      username: mail
      # "DN" (case sensitive) is a special attribute name. It indicates that
      # this value should be taken from the entity's DN not an attribute on
      # the entity.
      idAttr: DN
      emailAttr: mail
      nameAttr: cn

    groupSearch:
      baseDN: ou=Groups,dc=example,dc=org
      filter: "(objectClass=groupOfNames)"

      userMatchers:
        # A user is a member of a group when their DN matches
        # the value of a "member" attribute on the group entity.
      - userAttr: DN
        groupAttr: member

      # The group name should be the "cn" value.
      nameAttr: cn

staticClients:
- id: vikunja
  redirectURIs:
   - 'https://my.vikunja.com/auth/openid/'
  name: 'Vikunja'
  secret: mySecretIDisGood 

frontend:
  dir: /opt/dex/web
  issuer: my-dex
  extra:
    tos_footer_link: "https://my-ldapp.com/terms"
    client_logo_url: "../theme/client-logo.png"
    #foo: "bar"
```

### Logs

```shell
404 Page not found
```
