### ISSUE TITLE
After changing the config, the client is not authorized

### ISSUE THREAD

**Issue by ekrasnoyarov** [dexidp/dex#2722]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.35.3

### Storage Type

Kubernetes

### Installation Type

Official Helm chart

### Expected Behavior

I have added a new client or changed the current client and in my application returns to the authorization page.

### Actual Behavior

App + keycloak gatekeeper proxy + dex , when first created, dex works fine, if you change anything in the config dex, for example, the client's name or secret, or add another static client, then in my application after authorization returns to the authorization page.

Kubernetes version 1.22
Keycloak-gatekeeper: latest
App:  NGINX_VERSION=1.19.10 + NJS_VERSION=0.5.3

### Steps To Reproduce

1. Added a new client to the config
2. Applied a new config in my kubernetes cluster 
3. Login my web app

### Configuration

```yaml
config: |-
            issuer: https://dex.test.example.ru
            storage:
                type: kubernetes
                config:
                  inCluster: true

            web:
                http: 0.0.0.0:5556

                # If enabled, be sure to configure tls settings above, or use a tool
                # such as let-encrypt to manage the certs.
                # Currently this chart does not support both http and https, and the port
                # is fixed to 5556
                #
                # https: 0.0.0.0:5556
                # tlsCert: /etc/dex/tls/tls.crt
                # tlsKey: /etc/dex/tls/tls.key

            frontend:
                theme: "coreos"
                issuer: "Cloud"
                issuerUrl: "https://dex.test.example.ru
                logoUrl: https://argocd.test.example.ru/api/dex/theme/logo.png

            expiry:
                signingKeys: "6h"
                idTokens: "24h"
                refreshTokens:
                  disableRotation: true
                  absoluteLifetime: 876000h
                  validIfNotUsedFor: 4392h

            logger:
                level: debug
                format: json

            oauth2:
                responseTypes: ["code", "token", "id_token"]
                skipApprovalScreen: true

            # Remember you can have multiple connectors of the same 'type' (with different 'id's)
            # If you need e.g. logins with groups for two different Microsoft 'tenants'
            connectors:
              - type: ldap
                id: ldap
                name: LDAP
                config:
                  insecureSkipVerify: true
                  insecureNoSSL: true
                  startTLS: false
                  host: test.example.ru:389
                  bindDN: 'CN=ldap,OU=TEST,OU=TEST,DC=test,DC=example,DC=ru'
                  bindPW: <path:test/data/test#ldapPassword>
                  usernamePrompt: login
                  userSearch:
                    baseDN: "DC=test,DC=example,DC=ru"
                    filter: "(objectClass=person)"
                    username: sAMAccountName
                    idAttr: cn
                    emailAttr: sAMAccountName
                    nameAttr: cn
                  groupSearch:
                    baseDN: "DC=test,DC=example,DC=ru"
                    filter: "(objectClass=group)"
                    userMatchers:
                    - userAttr: DN
                      groupAttr: member
                    nameAttr: cn
            staticClients:
              - id: <path:test/data/test#dexClient> #vault
                name: <path:test/data/test#dexClient>
                secret: <path:test/data/test#dexClientSecret>
                redirectURIs:
                - https://dev.test.example.ru/oauth/callback             
            enablePasswordDB: False
      - name: VAULT_ADDR
        value: http://vault-system.vault-system.svc.cluster.local:8200
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

### Logs

```shell
app log:
{"remote_addr":"10.0.3.80","remote_user":"","time_local":"27/Oct/2022:09:35:26 +0000","request":"GET /k8s-api/apis/example.ru/v1/informationsystems HTTP/1.1","status": "403","body_bytes_sent":"406","http_referrer":"https://dev.test.example.ru/","http_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","request_time":"0.022"}
{"remote_addr":"10.0.3.80","remote_user":"","time_local":"27/Oct/2022:09:35:26 +0000","request":"GET /k8s-api/ouath/refresh HTTP/1.1","status": "403","body_bytes_sent":"242","http_referrer":"https://dev.test.example.ru/","http_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36","request_time":"0.017"}

keycloak gatekeeper log:

4
1.6668633420747137e+09  error   state in cookie and url query parameter do not match    {"cookie-state": "7b3226c2-3940-4aab-9b42-2e6b2c1eb6fb", "url-state": "4ab4f5ca-97fb-4165-b1c1-45fa487a9ed7"}
1.6668633420747993e+09  warn    state parameter mismatch        {"http_status": 403}
1.6668633420825372e+09  warn    user forbidden access   {"extra_messages": ["unable to exchange code for access token", "invalid_request: redirect_uri did not match URI from initial request."]}
1.666863342082645e+09   warn    unable to exchange code for access token invalid_request: redirect_uri did not match URI from initial request.  {"http_status": 403}

dex has no errors
```
