### ISSUE TITLE
Support for parsing userID, username, etc out of nested JSON objects

### ISSUE THREAD

**Issue by jwtrhs** [dexidp/dex#2778]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

I have been trying to use SourceHut as an OAuth2 connector in Dex. My problem is that SourceHut's API uses GraphQL which returns user information in a nested JSON object.

What I've got so far, I'm trying to use the following connector:
```yaml
- type: oauth
  id: sourcehut
  name: SourceHut
  config:
    clientID: $SOURCEHUT_CLIENT_ID
    clientSecret: $SOURCEHUT_CLIENT_SECRET
    redirectURI: https://dex.example.com/callback
    tokenURL: https://meta.sr.ht/oauth2/access-token
    authorizationURL: https://meta.sr.ht/oauth2/authorize
    userInfoURL: https://meta.sr.ht/query?query={me{id%20username%20email%20canonicalName}}
    scopes:
      - meta.sr.ht/PROFILE:RO
    userIDKey: data.me.id
```

The `userInfoURL` is a GraphQL endpoint that returns something like:
```json
{
  "data": {
    "me": {
      "id": 1,
      "username": "jwtrhs",
      "email": "jon@example.com",
      "canonicalName": "~jwtrhs"
    }
  }
}
```

I can see in the code that the `userIDKey` is expecting only a top-level key, not nested. So of course my attempt at using `data.me.id` fails.

### Proposed Solution

Some way to specify a `userIDKey` and other claims that can parse data out of a nested JSON structure. The "dot" notation I've tried would conflict with keys that actually have dots in them. Maybe a nested YAML definition?

```yaml
userIDKey:
  data:
    me: id
```
