### ISSUE TITLE
dexitp chart fails with errors although microsoft connector block is configured 

### ISSUE THREAD

**Issue by rzvn2600** [dexidp/dex#2888]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.35.3

### Storage Type

Kubernetes

### Installation Type

Official Helm chart

### Expected Behavior

I expect that if the following block is configured that dex POD at least will be up and running.

`dex-5d64f96b5b-4xnhm                                  0/1     CrashLoopBackOff   253 (3m35s ago)   21h`

Config block added:

```
# -- Application configuration.
# See the [official documentation](https://dexidp.io/docs/).
config: 
  connectors:
  - type: microsoft
    # Required field for connector id.
    id: microsoft
    # Required field for connector name.
    name: Microsoft
    config:
      # Credentials can be string literals or pulled from the environment.
      clientID: __TEMP__
      clientSecret: __TEMP__
      redirectURI: http://127.0.0.1:5556/dex/callback
      tenant: myorg.onmicrosoft.com
      groups:
        - developers
        - devops
      # All relevant E-Mail Adresses delivered by AD will transformed to
      # lowercase if config is TRUE
      emailToLowercase: true
```

### Actual Behavior

POD is in fails state with errors that cannot be found in documentation only in code. This does not help with anything

```
❯ k logs dex-5d64f96b5b-4xnhm
time="2023-04-06T12:39:45Z" level=info msg="Dex Version: v2.35.3-dirty, Go Version: go1.19.2, Go OS/ARCH: linux amd64"
invalid Config:
	-	no issuer specified in config file
	-	no storage supplied in config file
```

### Steps To Reproduce

1. Download chart from https://github.com/dexidp/helm-charts/tree/master/charts/dex
2. Fill the connector configuration 
3. Deploy with Helm 
4. Search error with 3 results in the whole world on Google. None of the errors described by any user and just pointing to your code 

### Additional Information

Please let me know if there is anything that I have to do more to get this to work. I added the connector for microsoft and in the documentation there is nothing else required.

### Configuration

```yaml
issuer: there is nothing with issuer specified int he values file
storage: why should I define storage mounts. there is nothing related with storage required in the documentation only when mounting f.e. okta pem file 
connector:


# -- Application configuration.
# See the [official documentation](https://dexidp.io/docs/).
config: 
  connectors:
  - type: microsoft
    # Required field for connector id.
    id: microsoft
    # Required field for connector name.
    name: Microsoft
    config:
      # Credentials can be string literals or pulled from the environment.
      clientID: __TEMP__
      clientSecret: __TEMP__
      redirectURI: http://127.0.0.1:5556/dex/callback
      tenant: myorg.onmicrosoft.com
      groups:
        - developers
        - devops
      # All relevant E-Mail Adresses delivered by AD will transformed to
      # lowercase if config is TRUE
      emailToLowercase: true
```
```


### Logs

```shell
❯ k logs dex-5d64f96b5b-4xnhm
time="2023-04-06T12:39:45Z" level=info msg="Dex Version: v2.35.3-dirty, Go Version: go1.19.2, Go OS/ARCH: linux amd64"
invalid Config:
	-	no issuer specified in config file
	-	no storage supplied in config file
```
