### ISSUE TITLE
Microsoft connector clientId is too long when hashed to a k8s resource name

### ISSUE THREAD

**Issue by dermicus-miclip** [dexidp/dex#2904]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.36.0

### Storage Type

Kubernetes

### Installation Type

Official Helm chart

### Expected Behavior

I expect that it can work with a newly created microsoft clientId when configuring it through the helm chart values as a connector.

### Actual Behavior

It gets a database error, saying that the client id is invalid.

### Steps To Reproduce

Configure a microsoft connector with a newly created clientId.
MS in my case provided a UUID v4, which, when hashed is > 63 characters.

### Additional Information

See the following test that fails:
https://github.com/dermicus-miclip/dex/commit/bc0651565dd884da0b2739dfd43a582816d14441.

That is the root cause of this issue when using k8s storage.

Helm chart version: 0.14.1

### Configuration

```yaml
config:
    issuer: https://dex.miclip-internal.mydev.local
    storage:
      type: kubernetes
      config:
        inCluster: true
    connectors:
      - type: microsoft
        # Required field for connector id.
        id: microsoft
        # Required field for connector name.
        name: Microsoft
        config:
          # Credentials can be string literals or pulled from the environment.
          clientID: fb407785-2479-4216-94a7-27f4e031e134
          clientSecret: ####
          redirectURI: https://dex.miclip-internal.mydev.local/callback
```
