### ISSUE TITLE
Connector Error

### ISSUE THREAD

**Issue by alessiodimatteo93** [dexidp/dex#3061]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.32.0

### Storage Type

Kubernetes

### Installation Type

Official container image

### Expected Behavior

I have configured the dex-ldap yaml to point to a LDAP server, starting from the default yaml provided by this repository. The expected results is that when I apply the yaml on my kubernetes cluster, the pods are running.

### Actual Behavior

The actual behavior is that the pods are in crashloop backoff with the following error:
(these are the pod logs)
time="2023-08-02T07:15:32Z" level=info msg="Dex Version: v2.32.0-dirty, Go Version: go1.18.3, Go OS/ARCH: linux amd64"
time="2023-08-02T07:15:32Z" level=info msg="config issuer: [http://******:5556/dex"](http://*******:5556/dex%22)
time="2023-08-02T07:15:32Z" level=info msg="kubernetes client apiVersion = dex.coreos.com/v1"
time="2023-08-02T07:15:32Z" level=info msg="creating custom Kubernetes resources"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource authcodes.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource authcodes.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource authrequests.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource authrequests.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource oauth2clients.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource oauth2clients.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource signingkeies.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource signingkeies.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource refreshtokens.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource refreshtokens.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource passwords.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource passwords.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource offlinesessionses.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource offlinesessionses.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource connectors.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource connectors.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource devicerequests.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource devicerequests.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource devicetokens.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource devicetokens.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="config storage: kubernetes"
time="2023-08-02T07:15:32Z" level=info msg="config connector: ldap"
time="2023-08-02T07:15:32Z" level=info msg="config refresh tokens rotation enabled: true"
failed to initialize server: server: Failed to open connector : failed to open connector: unknown connector type ""

### Steps To Reproduce

on my kubernetes cluster
with the config provided below
then applied the configuration

### Configuration

```yaml
*The *** are sensitive information, they are actual endpoint*
---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex # This is created below
      containers:
      - image: ghcr.io/dexidp/dex:v2.32.0
        name: dex
          command: ["/usr/local/bin/dex", "serve","/etc/dex/cfg/config-ldap.yaml"]
        ports:
        - name: https
          containerPort: 5556

        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        - name: tls
          mountPath: /etc/dex/tls

        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-client
              key: client-id
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-client
              key: client-secret

        readinessProbe:
          httpGet:
            path: /healthz
            port: 5556
            scheme: HTTPS
      volumes:
      - name: config
        configMap:
          name: dex
          items:
          - key: config-ldap.yaml
            path: config-ldap.yaml
      - name: tls
        secret:
          secretName: dex.example.com.tls
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
  namespace: dex
data:
  config-ldap.yaml: |
    issuer: http://*****:5556/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
        namespace: dex

    web:
      http: 0.0.0.0:5556

    connectors:
    - type: ldap
      name: OpenLDAP
      id: ldap
      config:
        config:
        # The following configurations seem to work with OpenLDAP:
        #
        # 1) Plain LDAP, without TLS:
        host: *******:389
        insecureNoSSL: true
        #
        # 2) LDAPS without certificate validation:
        #host: localhost:636
        #insecureNoSSL: false
        #insecureSkipVerify: true
        #
        # 3) LDAPS with certificate validation:
        #host: YOUR-HOSTNAME:636
        #insecureNoSSL: false
        #insecureSkipVerify: false
        #rootCAData: 'CERT'
        # ...where CERT="$( base64 -w 0 your-cert.crt )"

        # This would normally be a read-only user.
        #bindDN: cn=admin,dc=example,dc=org
        #bindPW: admin
        bindDN: "CN=admin,CN=Users,DC=mydomain,DC=local"
        bindPW: *****
        usernamePrompt: Email Address

        userSearch:
          #baseDN: ou=People,dc=example,dc=org
          baseDN: OU=BPM,OU=Test,OU=Gruppi_Applicativi,OU=Companies,DC=*****,DC=it
          filter: "(objectClass=person)"
          baseDN: "OU=BPM,OU=Test,OU=Gruppi_Applicativi,OU=Companies,DC=*****,DC=it"
          #username: mail
          # "DN" (case sensitive) is a special attribute name. It indicates that
          # this value should be taken from the entity's DN not an attribute on
          # the entity.
          idAttr: dn
          emailAttr: mail
          nameAttr: cn

        groupSearch:
          #baseDN: ou=Groups,dc=example,dc=org
          baseDN: OU=BPM,OU=Test,OU=Gruppi_Applicativi,OU=Companies,DC=*****,DC=it
          filter: "(objectClass=groupOfNames)"

          userMatchers:
            # A user is a member of a group when their DN matches
            # the value of a "member" attribute on the group entity.
          - userAttr: dn
            groupAttr: member

          # The group name should be the "cn" value.
---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: dex
spec:
  type: NodePort
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: 5556
    nodePort: 32000
  selector:
    app: dex
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: dex
  name: dex
  namespace: dex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dex
rules:
- apiGroups: ["dex.coreos.com"] # API group created by dex
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create"] # To manage its own resources, dex must be able to create customresourcedefinitions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dex
subjects:
- kind: ServiceAccount
  name: dex           # Service account assigned to the dex pod, created above
  namespace: dex  # The namespace dex is running in
```

### Logs

```shell
time="2023-08-02T07:15:32Z" level=info msg="Dex Version: v2.32.0-dirty, Go Version: go1.18.3, Go OS/ARCH: linux amd64"
time="2023-08-02T07:15:32Z" level=info msg="config issuer: [http://******:5556/dex"](http://*******:5556/dex%22)
time="2023-08-02T07:15:32Z" level=info msg="kubernetes client apiVersion = dex.coreos.com/v1"
time="2023-08-02T07:15:32Z" level=info msg="creating custom Kubernetes resources"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource authcodes.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource authcodes.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource authrequests.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource authrequests.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource oauth2clients.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource oauth2clients.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource signingkeies.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource signingkeies.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource refreshtokens.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource refreshtokens.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource passwords.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource passwords.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource offlinesessionses.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource offlinesessionses.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource connectors.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource connectors.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource devicerequests.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource devicerequests.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="checking if custom resource devicetokens.dex.coreos.com has already been created..."
time="2023-08-02T07:15:32Z" level=info msg="The custom resource devicetokens.dex.coreos.com already available, skipping create"
time="2023-08-02T07:15:32Z" level=info msg="config storage: kubernetes"
time="2023-08-02T07:15:32Z" level=info msg="config connector: ldap"
time="2023-08-02T07:15:32Z" level=info msg="config refresh tokens rotation enabled: true"
failed to initialize server: server: Failed to open connector : failed to open connector: unknown connector type ""
```
