### ISSUE TITLE
Legacy field 'org' works but recommended 'orgs' field structure fails with github connector

### ISSUE THREAD

**Issue by vishaalsin** [dexidp/dex#3062]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.31.2

### Storage Type

Kubernetes

### Installation Type

Official container image

### Expected Behavior

Users in the github org should be able to successfully login with oauth.

### Actual Behavior

Users ends up in the following error - **failed to authenticate: github: "github-user" user not in required orgs or teams**

### Steps To Reproduce

Install kubeflow with dex for logging in to the central dashboard. Use github connector to enable github based login for users in the org.

 the following config works:
```
connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: *****************
        clientSecret: ************************
        redirectURI: https://*****************/dex/callback
        org: ****
```
but this one does not. (It ends up in the following error - **failed to authenticate: github: user not in required orgs or teams**):
```
connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: ******************
        clientSecret: *********************
        redirectURI: https://*****************/dex/callback
        orgs:
        - name: ***
```
The teams configuration is taken from [here](https://dexidp.io/docs/connectors/github/#configuration) 

### Additional Information

kubeflow manifests version : v1.6

### Configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    issuer: https://*******************/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $CLIENT_ID
        clientSecret: $CLIENT_SECRET
        redirectURI: https://*********************/dex/callback
        orgs:
        - name: ***
        loadAllGroups: false
    enablePasswordDB: true
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/login/oidc"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
```

### Logs

```shell
failed to authenticate: github: "github-user" user not in required orgs or teams
```
