### ISSUE TITLE
Dex config map to pick staticClients.id , secret from environment variable

### ISSUE THREAD

**Issue by BrijeshBurfal** [dexidp/dex#3211]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.37.0

### Storage Type

Kubernetes

### Installation Type

Official Helm chart, Custom Helm chart

### Expected Behavior

   When we setup env and secret in dex deployment 
   the config map should pick environment variable in
    staticClients:
    - id: '${SSO_CLIENT_ID}'
      redirectURIs:
      - 'https://argo-ewd.namespace.extdns.dev.corporate.com/oauth2/callback'
      name: 'Argo Workflow'
      secret: '${SSO_CLIENT_SECRETS}'

      https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml#L101
      this should be able to pick secret environment variable

### Actual Behavior

The 
    staticClients:
    - id: '${SSO_CLIENT_ID}' // gives error while parsing 
      redirectURIs:
      - 'https://argo-ewd.namespace.extdns.dev.corporate.com/oauth2/callback'
      name: 'Dex Dev'
      secret: '${SSO_CLIENT_SECRETS}' // gives error while parsing 
      
   while in the same config map the connector section is able to parse the secret 
  connectors :
    config:
    clientId: ${SSO_CLIENT_ID}  // able to fetch secret env and works
    secretID: ${SSO_CLIENT_SECRETS}' // able to fetch secret env and works

### Steps To Reproduce

write a deployment file
https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml
kubectl apply dex

### Additional Information

https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml#L101
when we hardcode the value for staticclient client id and  secret it works .

### Configuration

```yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dex-config
  namespace: corp
data:
  config.yaml: |
    issuer: https://dex-ewd.corp.extdns.dev.corp.com/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      # http: 0.0.0.0:5556
      https: 0.0.0.0:5557
      tlsCert: /etc/dex/ssl/tls.crt
      tlsKey: /etc/dex/ssl/tls.key
      caCert: /etc/dex/ssl/ca.crt
    # Configuration for telemetry
    telemetry:
      https: 0.0.0.0:5558
    staticClients:
    - id: '${SSO_CLIENT_ID}'
      redirectURIs:
      - 'https://argo-ewd.corp.extdns.dev.corp.com/oauth2/callback'
      name: 'Argo Workflow '
      secret: '${SSO_CLIENT_SECRETS}'
    enablePasswordDB: true
    connectors:
    - type: oidc
      id: microsoft
      name: Microsoft
      config:
        issuer: https://login.microsoftonline.com/${SSO_DEX_TENANT}/v2.0
        # Connector config values starting with a "$" will read from the environment.
        clientID: ${SSO_CLIENT_ID}
        clientSecret: ${SSO_CLIENT_SECRETS}
        # Dex's issuer URL + "/callback"
        redirectURI: 'https://dex-ewd.corp.extdns.dev.corp.com/dex/callback'
        insecureSkipEmailVerified: true 
        scopes:
         - profile
         - email
         - openid
        # Groups claims (like the rest of oidc claims through dex) only refresh when the id token is refreshed
        insecureEnableGroups: true
```

### Logs

```shell
"Failed to get client: invalid kubernetes resource name: must match the pattern ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0- │
│ level=error msg="Failed to parse authorization request: Database error."
```
