### ISSUE TITLE
Upstream release from v2.35.3 to v2.38.0 removes envinronment variable configuration for dex deployment

### ISSUE THREAD

**Issue by Andrei-sys** [dexidp/dex#3369]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Upstream release from v2.35.3 to v2.38.0 removes envinronment variable configuration for dex deployment.
Code snippet that upstream release would remove:
```yaml
          env:
            {{- if (.Values.configSecret.enableOpenShiftConfig) }}
            - name: OPENSHIFT_OAUTH_CLIENT_ID
              value: system:serviceaccount:{{.Release.Namespace}}:{{include "dex.serviceAccountName" .}}
            - name: OPENSHIFT_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ include "dex.serviceAccountName" . }}-token"
                  key: token
            {{- end }}
```

### Proposed Solution

Is this required for being removed for good in the upstream chart deployment, meaning I would need to find another way of importing it? If yes, any input is highly appreciated. Thank you!
