### ISSUE TITLE
Provide support for github apps

### ISSUE THREAD

**Issue by blixem777** [dexidp/dex#3427]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

From the [docs](https://dexidp.io/docs/connectors/github/), it seems there is support for github [oauth2 apps](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app), but not for [github apps](https://docs.github.com/en/apps/using-github-apps/installing-your-own-github-app).

Since github is recommending using github aps instead, it would be great if there was support for that in dex.

### Proposed Solution

Something like the below:
```
connectors:
- type: github
  id: github
  name: GitHub
  config:
    appID: YOUR_APP_ID_FROM_GITHUB
    appPrivateKeyPath: /path/to/your/private-key.pem
    ...
```
