### ISSUE TITLE
device auth flow, incorrect redirect_uri towards oidc provider

### ISSUE THREAD

**Issue by araker** [dexidp/dex#3798]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.41.1 (docker latest)

### Storage Type

Postgres

### Installation Type

Official container image

### Expected Behavior

I'm testing out the device authorization code grant on a local install, with example app and 2 oidc providers (aws cognito) have been activated. 

First step is to call
 ```
curl -X POST http://localhost:5556/dex/device/code \
     -H 'Content-Type: application/x-www-form-urlencoded' \
     -d 'client_id=example-app&scope=openid+profile+email+offline_access)
 
```
This gives me back a page where the device code can be filled in. After filling in this code a redirect to the oidc provider is made, when clicking on a provider I expect to be able to login and give permission to the device to be able to login using the account specified.

### Actual Behavior

Step 1 works fine, after filling in the device code I get the error message 'Unregistered redirect_uri ("/device/callback")'. For my oidc provider, aws cognito, it is not possible to register non valid url callbacks. I would expect the redirect_uri to have the issuer url included, e.g. http://localhost:5556/dex/device/callback. 

The call made to the oidc provider is the following
`http://localhost:5556/dex/auth/cognito-oidc-a?client_id=example-app&client_secret=&redirect_uri=%2Fdevice%2Fcallback&response_type=code&scope=openid+profile+email+offline_access&state=PBNB-TMVC
`

### Additional Information

I see in the [source](https://github.com/dexidp/dex/blob/e1407a455ce48035c5dce13e0904b1daab4d63ea/server/deviceflowhandlers.go#L436) that this redirect_uri is hardcoded.

### Configuration

```yaml
issuer: http://localhost:5556/dex
storage:
  type: postgres
  config:
    host: localhost
    port: 5432
    database: dex_db
    user: dex
    password: xxxx
    ssl:
      mode: disable
web:
  http: 0.0.0.0:5556
staticClients:
  - id: example-app
    redirectURIs:
      - "http://localhost:5555/callback"
    name: "Example App"
    secret: xxxx
enablePasswordDB: true
oauth2:
  skipApprovalScreen: true
  alwaysShowLoginScreen: false
  grantTypes: ["implicit", "refresh_token", "authorization_code", "urn:ietf:params:oauth:grant-type:device_code"]
  responseTypes: ["code", "token", "id_token"]
staticPasswords:
  - email: "admin@example.com"
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
connectors:
 - type: oidc
   id: cognito-oidc-a
   name: Cognito-oidc-a
   config:
     issuer: https://cognito-idp.eu-central-1.amazonaws.com/some-userpool-id
     clientID: some-client-id
     clientSecret: some-client-secret
     redirectURI: http://localhost:5556/dex/callback
     getUserInfo: true
     claimMapping:
      name: "cognito:username"
     insecureSkipEmailVerified: true
 - type: oidc
   id: cognito-oidc-b
   name: Cognito-oidc-b
   config:
     clientID: some id
     clientSecret: some-secret
     issuer: https://cognito-idp.eu-central-1.amazonaws.com/some-userpool-id
     redirectURI: http://localhost:5556/dex/callback
     getUserInfo: true
     claimMapping:
       name: email
     insecureSkipEmailVerified: true
```

**Comment by nabokihms** [comment]
The `/device/callback` is the URL that you need to add to your staticClients settings. See the example: https://github.com/dexidp/dex/blob/80be9bca0fd3600c6e3924a5e79481b09590ae8d/examples/config-dev.yaml#L128-L138

**Comment by araker** [comment]
Thanks for clarifying that, I missed that part. The flow now works beautifully.

**Comment by yashg-op** [comment]
Hi guys @araker @nabokihms,

We urgently require to implement Dex with the OIDC connector. We have been facing this issue where it says:

```
Not found, invalid client_id ("")
```

Help would be greatly appreciated, couldn't find anything decisive anywhere, only open issues and unanswered discussions.

![Image](https://github.com/user-attachments/assets/0a39b252-8bdb-4cfb-9301-70e0cd93948e)

Below is the config:

```yaml
connectors:
  - config:
      clientID: CLIENT_ID
      clientSecret: CLIENT_SECRET
      insecureEnableGroups: true
      issuer: https://dev-88813151.okta.com/oauth2/default
      redirectURI: https://dex.optiq.one/callback
      scopes:
        - profile
        - email
        - groups
    id: okta
    name: Okta
    type: oidc
issuer: https://dex.optiq.one/
logger:
  level: debug
oauth2:
  alwaysShowLoginScreen: true
storage:
  config:
    inCluster: true
  type: kubernetes
web:
  allowedOrigins:
    - '*'
  http: 0.0.0.0:5556
```
