### ISSUE TITLE
failed to initialize storage: failed to perform migrations: creating migration table: unable to open database file: no such file or directory

### ISSUE THREAD

**Issue by droplet-js** [dexidp/dex#3900]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.41.1

### Storage Type

SQLite

### Installation Type

Official container image

### Expected Behavior

it work well

### Actual Behavior

time=2024-12-30T14:05:03.635Z level=INFO msg="Version info" dex_version=v2.41.1 go.version=go1.22.5 go.os=linux go.arch=amd64
time=2024-12-30T14:05:03.635Z level=INFO msg="config issuer" issuer=https://dex.mydomain.com
failed to initialize storage: failed to perform migrations: creating migration table: unable to open database file: no such file or directory

### Steps To Reproduce

1. on centos (it work well on mac)
2. run docker-compose up -d

### Configuration

```yaml
docker-compose.yaml

  dex:
    container_name: dex
    image: ghcr.io/dexidp/dex:v2.41.1
    restart: unless-stopped
    hostname: dex
#    ports:
#      - 5556
    extra_hosts:
      - host.docker.internal:host-gateway
    configs:
      - source: dex_config
        target: /etc/dex/config.yaml
    volumes:
      - ../dev-ops-repo/dex/data:/data
    environment:
      - DEX_LOG_LEVEL=debug
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dex.loadbalancer.server.port=5556"
      - "traefik.http.routers.dex.service=dex"
      - "traefik.http.routers.dex.rule=Host(`dex.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.dex.entrypoints=websecure"

configs:
  dex_config:
    content: |
      issuer: https://dex.${SERVER_DOMAIN:-localhost}
      storage:
        type: sqlite3
        config:
          file: /data/dex.db
      web:
        http: 0.0.0.0:5556
      connectors:
      - type: oauth
        id: wecom
        name: WeCom
        config:
          clientID: xxx
          clientSecret: xxx
          redirectURI: https://dex.${SERVER_DOMAIN:-localhost}/callback
          tokenURL: https://qyapi.weixin.gq.com/cgi-bin/gettoken?corpid=xxx&corpsecret=xxx
          authorizationURL: https://login.work.weixin.qq.com/wwlogin/sso/login?login_type=CorpApp&appid=xxx&agentid=xxx
          userInfoURL: https://qyapi.weixin.qq.com/cgi-bin/auth/getuserinfo
          scopes:
            - snsapi_base
      oauth2:
        skipApprovalScreen: true
        alwaysShowLoginScreen: false
      staticClients:
      - id: whoami
        name: whoami
        secret: xxx
        redirectURIs:
        - https://whoami.${SERVER_DOMAIN:-localhost}/callback
```

### Logs

```shell
time=2024-12-30T14:05:03.635Z level=INFO msg="Version info" dex_version=v2.41.1 go.version=go1.22.5 go.os=linux go.arch=amd64
time=2024-12-30T14:05:03.635Z level=INFO msg="config issuer" issuer=https://dex.mydomain.com
failed to initialize storage: failed to perform migrations: creating migration table: unable to open database file: no such file or directory
```

**Comment by nabokihms** [comment]
Hello, @droplet-js. I don't think the problem is related to dex itself rather than the environment is is running in.

**Comment by hoogenm** [comment]
I got this error message as well when using a dexidp/dex Docker image: most folders in the container were not writable for the user running dex; setting the `.db` file location to the folder /var/dex worked to circumvent the (error) message. 

```
storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db
```
