### ISSUE TITLE
federated:id claims returns an error when used with OIDC

### ISSUE THREAD

**Issue by agaudreault** [dexidp/dex#3959]
### Version

2.41.1

### Installation Type

Official Helm chart

### Expected Behavior

The [documentation](https://dexidp.io/docs/configuration/custom-scopes-claims-clients/) states that the `federated:id` special claims should be supported for OAuth2 and OIDC. 

The goal would be to be able to always have the `federated_claims` on the token returned by dex, no matter which connector is used.

However, this does not seem to be configurable globally in https://github.com/dexidp/dex/blob/master/cmd/dex/config.go. 

### Actual Behavior

It returns an error when used with OIDC connector 

### Steps To Reproduce

Dex config
```yaml
    connectors:
    - type: oidc
      id: test
      name: Test connector
      config:
        insecureSkipEmailVerified: true
        insecureEnableGroups: true
        issuer: $issuer
        clientID: $clientID
        clientSecret: $clientSecret
        redirectURI: $dexUrl/callback
        scopes:
          - profile
          - email
          - groups
          - federated:id
```

Logs
```
{"time":"2025-01-30T21:18:27.349390204Z","level":"ERROR","msg":"failed to authenticate","err":"invalid_scope: The requested scope is invalid, unknown, malformed, or exceeds that which the client is permitted to request."}
```

It seems the error is caused by the scope being sent to our $issuer authorization_endpoint
```
<ISSUER_AUTHORIZATION_ENDPOINT>?client_id=<CLIENT_ID>&redirect_uri=<DEX_URL>%2Fcallback&response_type=code&scope=openid+profile+email+groups+federated%3Aid&state=<STATE>
```
