### ISSUE TITLE
authproxy connector: add support for specifying group header separator

### ISSUE THREAD

**Issue by a-buck** [dexidp/dex#3999]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.

### Problem Description

This issue proposes making the group header splitter configurable so a value other than `,` can be used.

This is motivated as the groups header is not universally a `,`. For example the default group separator in mod_auth_mellon is `;`.

To give a very specific example of how it would be useful, this would enable use of the dex integration for SSO in argocd, where the groups are not separated with a comma.

```yaml
# https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#dex

argo-cd:
  dex:
    enabled: true

  configs:
    cm:
      dex.config: |
        connectors:
        - type: authproxy
          id: corpproxy
          name: corpproxy
          config:
            userHeader: SSO-User
            groupHeader: SSO-Groups
            groupHeaderSeparator: ";"
```

### Proposed Solution

- groupHeaderSeparator is added as a configurable option for the authproxy connector
- the change is backwards compatible - maintaining `,` as a default

### Additional Information

please see https://github.com/dexidp/dex/pull/3745 for example implementation, happy to revive the PR if there is feedback.
