### ISSUE TITLE
Machine-to-machine authentication error Azure Entra ID

### ISSUE THREAD

**Issue by marcelo-modolo** [dexidp/dex#4012]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.39.1

### Storage Type

Postgres

### Installation Type

Official Helm chart

### Expected Behavior

Hi!
We read and followed the [documentation](https://dexidp.io/docs/guides/token-exchange/) for machine-to-machine authentication, but using Azure (Entra ID).
Below is the created configuration
```
- name: azure-entra-id
  type: oidc
  id: azure-entra-id
  config:
    issuer: https://sts.windows.net/{tenant_id}/
    issuerAlias: https://login.microsoftonline.com/{tenant_id}/
    scopes:
      - openid
      - profile
    userNameKey: sub
    getUserInfo: true
```
The connector is configured successfully!
{"level":"info","msg":"config connector: azure-entra-id","time":"2025-02-25T14:02:58Z"}

### Actual Behavior

Although the token generated in Azure is valid, we receive the following error when trying to authenticate
{"level":"error","msg":"failed to verify subject token: oidc: error loading userinfo: 400 Bad Request: ","time":"2025-02-21T22:56:31Z"}

{"level":"info","msg":"Dex Version: v2.39.1, Go Version: go1.22.2, Go OS/ARCH: linux amd64","time":"2025-02-25T14:02:58Z"}

### Configuration

```yaml

```

### Logs

```shell

```
