### ISSUE TITLE
LDAP Client Certificate Authentication is Ignored in Dex

### ISSUE THREAD

**Issue by crafa2** [dexidp/dex#4025]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.42.0

### Storage Type

Kubernetes

### Installation Type

Official Helm chart

### Expected Behavior

If a client certificate is provided (clientCert and clientKey are set), Dex should use it for authentication instead of defaulting to an anonymous bind.
Dex should only attempt an anonymous bind if neither a client certificate nor bindDN/bindPW are provided.

### Actual Behavior

When a client certificate (clientCert and clientKey) is provided, Dex drops it before performing the LDAP query.
If bindDN and bindPW are not set, Dex defaults to an anonymous bind, ignoring the client certificate.
This results in failed authentication unless the LDAP server allows anonymous binds.
Even when a certificate is provided, there is no way to use it for authentication since Dex does not pass it along.

### Steps To Reproduce

1. Configure Dex with an LDAP connector that relies on **client certificate authentication**.  
2. Ensure no `bindDN` and `bindPW` are set, expecting the certificate to be used.  
3. Observe that Dex attempts an **anonymous bind** instead of using the client certificate.  
4. As a result, authentication fails unless anonymous binds are allowed on the LDAP server.

### Configuration

```yaml
issuer: https://rke2-controlplane:32000
    logger:
      level: debug
    storage:
      type: Kubernetes
      config:
        inCluster: true
    web:
      https: 0.0.0.0:5554
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    connectors:
    - type: ldap
      name: LDAP
      id: ldap
      config:
        host: ldap.google.com:636
        insecureSkipVerify: true
        
        # Certificats LDAP
        rootCA: /etc/dex/ldap/ldap_ca.crt
        clientCert: /etc/dex/ldap/client.crt
        clientKey: /etc/dex/ldap/client.key
        #No bindDN and no bindPW
        userSearch:
          baseDN: "ou=internal users with 2FA,ou=Users,dc=mediarithmics,dc=com"
          filter: "(objectClass=inetOrgPerson)"
          username: uid
          idAttr: uid
          emailAttr: mail
          nameAttr: cn
        
        groupSearch:
          baseDN: "ou=Groups,dc=mediarithmics,dc=com"
          filter: "(objectClass=groupOfNames)"
          userMatchers:
          - userAttr: DN
            groupAttr: member
          nameAttr: cn
```

### Logs

```shell
2FA,ou=Users,dc=mediarithmics,dc=com" scope=sub filter="(&(objectClass=inetOrgPerson)(uid=crafa))"
time=2025-03-03T14:24:11.301Z level=ERROR msg="no results returned for filter" connector.type=ldap connector.id=ldap filter="(&(objectClass=inetOrgPerson)(uid=crafa))"
time=2025-03-03T14:24:11.302Z level=ERROR msg="failed login attempt: Invalid credentials." user=crafa request_id=1d11f1dc-064d-4e97-9d27-4bd38677267f
```
