### ISSUE TITLE
Remove Trailing / from issuer url

### ISSUE THREAD

**Issue by JWilson45** [dexidp/dex#4036]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.42.0

### Storage Type

In-memory

### Installation Type

Official Helm chart

### Expected Behavior

no 404s when viewing anything other than the root

### Actual Behavior

when you set the config like this

```
config:
  issuer: https://<host>/
```

there is a double / which results in 404s.

ex: viewing the known hosts results in
https://<host>///.well-known/openid-configuration and a 404 is returned

removing the / from the issuer fixes this:

```
config:
  issuer: https://<host>
```

however it would be simpler to remove a trailing / for more painless deployments

### Steps To Reproduce

1. deploy dex using the official helm chart, adding the issuer url as shown above with the trailing slash `issuer: https://<host>/`
2. go to the UI and click on discovery. this will result in a 404
3. remove the trailing /
4. test again and the 404 is gone

### Configuration

```yaml
config:
  issuer: https://<hostname>/
  storage:
    type: memory
  enablePasswordDB: true
  staticPasswords:
    - email: "jason@example.com"
      hash: "<redacted>"
      username: "jason"
      userID: "0"
```

### Logs

```shell

```
