### ISSUE TITLE
Cannot customize templates in kubernetes deployment of dex

### ISSUE THREAD

**Issue by LongStoryMedia** [dexidp/dex#4160]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

2.43.1

### Storage Type

In-memory

### Installation Type

Official container image

### Expected Behavior

dex interprets symlinks properly when custom templates are created via config map

### Actual Behavior

```sh
failed to initialize server: server: failed to load web static: parse files: read templates/..data: is a directory
```

given 

```yaml
frontend:
  dir: /etc/dex/dex-templates
```

and
```yaml
          volumeMounts:
            - name: config-out
              mountPath: /etc/dex
            - name: dex-web
              mountPath: /etc/dex/dex-templates
            - name: dex-static
              mountPath: /etc/dex/dex-templates/static
            - name: dex-themes
              mountPath: /etc/dex/dex-templates/themes
            - name: dex-templates
              mountPath: /etc/dex/dex-templates/templates
...
      volumes:
        - name: config-in
          configMap:
            name: config
        - name: config-out
          emptyDir: {}
        - name: dex-templates
          configMap:
            name: dex-templates
        - name: dex-static
          configMap:
            name: dex-static
        - name: dex-themes
          configMap:
            name: dex-themes
        - name: dex-web
          configMap:
            name: dex-web
```

documentation around this is woefully inadequate.

### Steps To Reproduce

given this deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      initContainers:
        - name: render-config
          image: alpine:latest
          command:
            [
              "sh",
              "-c",
              "apk add --no-cache gettext && envsubst < /config-in/config.yaml > /config-out/config.yaml",
            ]
          env:
            - name: DEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: client-secret
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-admin-secret
                  key: LDAP_ADMIN_PASSWORD
          volumeMounts:
            - name: config-in
              mountPath: /config-in
              readOnly: true
            - name: config-out
              mountPath: /config-out
      containers:
        - name: dex
          image: ghcr.io/dexidp/dex:v2.43.1
          securityContext:
            runAsUser: 0 # 0 is the root user
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: config-out
              mountPath: /etc/dex
            - name: dex-web
              mountPath: /etc/dex/dex-templates
            - name: dex-static
              mountPath: /etc/dex/dex-templates/static
            - name: dex-themes
              mountPath: /etc/dex/dex-templates/themes
            - name: dex-templates
              mountPath: /etc/dex/dex-templates/templates
          ports:
            - containerPort: 5556
          args:
            - dex
            - serve
            - /etc/dex/config.yaml
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: DEX_LOG_LEVEL
              value: "debug"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap-admin-secret
                  key: LDAP_ADMIN_PASSWORD
      volumes:
        - name: config-in
          configMap:
            name: config
        - name: config-out
          emptyDir: {}
        - name: dex-templates
          configMap:
            name: dex-templates
        - name: dex-static
          configMap:
            name: dex-static
        - name: dex-themes
          configMap:
            name: dex-themes
        - name: dex-web
          configMap:
            name: dex-web
```
and this config (omitting other properties for brevity)
```yaml
frontend:
  dir: /etc/dex/dex-templates
```

config maps are scripted to use a local copy of dex's "web"
```sh
kubectl create configmap dex-web \
  -n auth \
  --from-file="$(dirname "$0")/web" \
  --dry-run=client -o yaml | kubectl apply -f - --wait=true

kubectl create configmap dex-templates \
  -n auth \
  --from-file="$(dirname "$0")/web/templates" \
  --dry-run=client -o yaml | kubectl apply -f - --wait=true

kubectl create configmap dex-static \
  -n auth \
  --from-file="$(dirname "$0")/web/static" \
  --dry-run=client -o yaml | kubectl apply -f - --wait=true

kubectl create configmap dex-themes \
  -n auth \
  --from-file="$(dirname "$0")/web/themes" \
  --dry-run=client -o yaml | kubectl apply -f - --wait=true

kubectl apply -f deployment.yaml
```

pod will fail to start due to the error "failed to initialize server: server: failed to load web static: parse files: read templates/..data: is a directory"

### Configuration

```yaml

```

### Logs

```shell

```
