### ISSUE TITLE
LDAP connector: cannot specify the subject as username

### ISSUE THREAD

**Issue by antoinetran** [dexidp/dex#4197]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/dexidp/dex/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/dexidp/dex/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/dex/issues/new/choose) without success.

### Version

0.22.1

### Storage Type

etcd

### Installation Type

Official Helm chart

### Expected Behavior

Token claim should contain subject with username.

### Actual Behavior

Current subject is: `CjR1aWQ9YW50b2luZS10cmFuXzQxOTEsb3U9dXNlcnMsZGM9bGlzYW1pc3Npb24sZGM9b3JnEgRsZGFw` which does not contain username. It makes it impossible to know who is behind that user, to make filter based on that field.

### Steps To Reproduce

1. In any kubernetes, deploy dex helm
2. configure a LDAP connector
3. deploy argo-workflows helm
4. configure argo to use Dex
5. connect to argo with a LDAP user
6. Look at argo user page: it indicates:
```
Issuer:
    argo-server

Subject:
    CjR1aWQ9YW50b2luZS10cmFuXzQxOTEsb3U9dXNlcnMsZGM9bGlzYW1pc3Npb24sZGM9b3JnEgRsZGFw

Groups:
    REDACTED

Service Account:
    REDACTED

Service Account Namespace:
    argo
```

### Configuration

```yaml
config:
  # See https://dexidp.io/docs/connectors/local/

  issuer: REDACTED

  # mapping of fields from the submitted token
  userNameKey: sn

  # Configuration for LISA Mission Directory (LMD).
  connectors:
  - type: ldap
    id: ldap
    name: LDAP-XXX

    config:
      # host and port of the LDAP server in form "host:port".
      host: REDACTED

      # If a custom certificate isn't provide, this option can be used to turn on
      # TLS certificate checks. As noted, it is insecure and shouldn't be used outside
      # of explorative phases.
      #
      # insecureSkipVerify: true
      insecureSkipVerify: false

      # When connecting to the server, connect using the ldap:// protocol then issue
      # a StartTLS command. If unspecified, connections will use the ldaps:// protocol
      #
      startTLS: false
      # The DN and password for an application service account. The connector uses
      # these credentials to search for users and groups. Not required if the LDAP
      # server provides access for anonymous auth.
      # Please note that if the bind password contains a `$`, it has to be saved in an
      # environment variable which should be given as the value to `bindPW`.
      bindDN: '${BIND_DN}'
      bindPW: '${BIND_PW}'

      # freeIPA server's CA
      #rootCA: ca.crt
      userSearch:
        # Would translate to the query "(&(objectClass=posixAccount)(uid=<username>))".
        baseDN: REDACTED
        filter: "REDACTED"
        # username attribute used for comparing user entries. This will be translated
        # and combined with the other filter as "(<attr>=<username>)".
        username: sn
        # The following three fields are direct mappings of attributes on the user entry.
        # String representation of the user.
        idAttr: dn
        # Maps to display name of users. No default value.
        nameAttr: displayName
        # Maps to preferred username of users. No default value.
        #preferredUsernameAttr:
        # Required. Attribute to map to Email.
        emailAttr: mail
        # Entity attribute to map to display name of users.
      groupSearch:
        # Would translate to the query "(&(objectClass=group)(member=<user uid>))".
        baseDN:REDACTED
        #filter: "(objectClass=group)"
        filter: "REDACTED"
        userMatchers:
        - userAttr: dn
```

### Logs

```shell
time=2025-06-27T09:33:12.135Z level=INFO msg="performing ldap search" connector.type=ldap connector.id=ldap base_dn="REDACTED" scope=sub filter="REDACTED"
time=2025-06-27T09:33:12.444Z level=INFO msg="username mapped to entry" connector.type=ldap connector.id=ldap username=REDACTED user_dn="REDACTED"
time=2025-06-27T09:33:12.656Z level=INFO msg="performing ldap search" connector.type=ldap connector.id=ldap base_dn="REDACTED" scope=sub filter="REDACTED"
time=2025-06-27T09:33:12.704Z level=INFO msg="login successful" connector_id=ldap username="REDACTED" preferred_username="" email=REDACTED groups="[REDACTED]" request_id=331a04e4-43ac-4943-9118-dbc0c39e8f61
```
