### ISSUE TITLE
examples/k8s: use ingress to route traffic to dex

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#753]
For real clusters, dex won't be exposed directly to the outside, it'll go through some sort of ingress controller. Make the example manifests do this. This also creates a cleaner point of customization, allowing users to re-purpose the examples by switching out the ingress for whatever their setup is.

Related to #682

Need to chat with @dghubble about possible setups.

**Comment by set321go** [comment]
An example of ingress using nginx `auth_request` would probably help a lot of people. Here is an example ingress I use with traefik  on gce. 

The important part here for proxying is `kubernetes.io/ingress.class: "traefik"` which prevents gce from wiring it up to an external LB, this is an adapted version found in nginx tutorials.

 ```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: pathprefixstrip
spec:
  rules:
  - host: demo.data-realm.com
    http:
      paths:
      - path: /admin/proxy
        backend:
         serviceName: traefik-web-ui
         servicePort: 80
```

One of the most difficult things i've found trying to learn dex is the documentation is not very 'real world' I know there are some tickets for this.
