### ISSUE TITLE
health checks: consider not failing health checks if the storage is unavailable

### ISSUE THREAD

**Issue by ericchiang** [dexidp/dex#853]
We've seen lots of cases where dex's backing storage is unavailable, dex fails its health check, and users think there's something wrong with dex. Maybe we should only fail health checks if we identify a problem on dex's end? For example if dex's credentials to the backing storage are invalid?

Are there best practices for these kind of situations?

cc @rithujohn191 @sym3tri

**Comment by nabokihms** [comment]
It was refactored:
1. `/healthz` works like the old health check.
2. `/healthz/live` proper health check, it doesn't depend on storage (returns 200).
3. `/healthz/ready` works like the old health check.


Kubernetes example of proper probes configuration:
```yaml
livenessProbe:
  httpGet:
    path: /healthz/live
    port: 5558
readinessProbe:
  httpGet:
    path: /healthz/ready
    port: 5558
```
