### ISSUE TITLE
Connector: AWS Cognito User Pool Support

### ISSUE THREAD

**Issue by philips** [dexidp/dex#965]
I attempted to create an [AWS Cognito User Pool](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-assign-domain.html) and access it via the OIDC connector. This didn't work as it seems the Cognito IdP isn't OIDC compliant. Here is what I attempted:

```
    connectors:
      - type: oidc
        id: cognito
        name: AWS Cognito
        config:
          issuer: 'https://cognito-idp.us-west-2.amazonaws.com/us-west-2_UllxWHhEV'

          clientID: stuff
          clientSecret: morestuff

          redirectURI: 'https://ca-central-1.a.ifup.org/identity/callback'
```

```
$ curl https://cognito-idp.us-west-2.amazonaws.com/us-west-2_UllxWHhEV/.well-known/openid-configuration
{
  "authorization_endpoint": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_UllxWHhEV",
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "issuer": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_UllxWHhEV",
  "jwks_uri": "https://cognito-idp.us-west-2.amazonaws.com/us-west-2_UllxWHhEV/.well-known/jwks.json",
  "response_types_supported": [
    "code",
    "id_token",
    "token id_token",
    "none"
  ],
  "subject_types_supported": [
    "public"
  ]
}
```

**Comment by chancez** [comment]
After a lot of digging in the docs,  I could only determine they might not support OIDC as an authentication flow, only SAML and regular OAuth2. But they do support federating to an OIDC provider, just not being one.

**Comment by philips** [comment]
@ericchiang says the `token_endpoint` field is missing per the OIDC spec.

**Comment by philips** [comment]
This is what dex's openid-configuration looks like for context:

```
{
  "issuer": "https://ca-central-1.example.com/identity",
  "authorization_endpoint": "https://ca-central-1.example.com/identity/auth",
  "token_endpoint": "https://ca-central-1.example.com/identity/token",
  "jwks_uri": "https://ca-central-1.example.com/identity/keys",
  "response_types_supported": [
    "code"
  ],
  "subject_types_supported": [
    "public"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "scopes_supported": [
    "openid",
    "email",
    "groups",
    "profile",
    "offline_access"
  ],
  "token_endpoint_auth_methods_supported": [
    "client_secret_basic"
  ],
  "claims_supported": [
    "aud",
    "email",
    "email_verified",
    "exp",
    "iat",
    "iss",
    "locale",
    "name",
    "sub"
  ]
}

```

**Comment by rithujohn191** [comment]
Yep writing a custom connector for it seems like the way to go.

**Comment by stefano-m** [comment]
For the record, as of today, Amazon Cognito can actually be used with dex as an OIDC connector.

What needs to be done is to configure the [App Client](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html) and [Domain](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-assign-domain.html) in the User Pool of choice. Dex will redirect to Cognito's login and the token will be returned to the client.

Note that I quickly tested this with the authorization flow only.

**Comment by jicowan** [comment]
@stefano-m can you post your config here?

**Comment by stefano-m** [comment]
@jicowan 

The connectors section of Dex's YAML configuration file should look like the following:

```yaml
connectors:
- type: oidc
  id: cognito
  name: AWS Cognito
  config:
    issuer: "https://cognito-idp.<AWS REGION>.amazonaws.com/<COGNITO USER POOL ID>"
    clientID: "<COGNITO APP CLIENT ID>"
    clientSecret: "<COGNITO APP CLIENT SECRET>"
    redirectURI: "<ISSUER URL>/callback"
    scopes:
      - openid
      - email
      - profile
```
Where

-    `<AWS REGION>` is the AWS region your user pool is in, e.g. eu-west-1
-    `<COGNITO USER POOL ID>` can be retrieved from the "General settings" page in the AWS Cognito console and looks something like `eu-west-1_iYUEhdSKA`
-    `<ISSUER URL>` is the value of the issuer setting in Dex's configuration file (usually at the top of the file) and looks something like `http://localhost:5556/dex`

Note that you must put the value of `redirectURI` in the "Callback URL(s)" field of the Cognito User Pool!
